### PR TITLE
Fix HdfsLocatedFileStatus and FileStatusWithmetadata class type conve…

### PR DESCRIPTION
**Pull request by zwq199400**
…rsion errors

# :mag: Description
## Issue References 🔗

This pull request fixes #

## Describe Your Solution 🔧

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pan3793** [comment]
Mind filling in the PR description about which issue you have faced?

**Comment by zwq199400** [comment]
When I connect to HIVE to read data, an error message will appear as follows:
`Caused by: java.lang.ClassCastException: org.apache.hadoop.hdfs.protocol.HdfsLocatedFileStatus cannot be cast to org.apache.spark.sql.execution.datasources.FileStatusWithMetadata
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.execution.datasources.FilePartition$.$anonfun$maxSplitBytes$2(FilePartition.scala:116)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
	at org.apache.spark.sql.execution.datasources.FilePartition$.maxSplitBytes(FilePartition.scala:116)
	at org.apache.kyuubi.spark.connector.hive.read.HiveScan.partitions(HiveScan.scala:89)
	at org.apache.spark.sql.execution.datasources.v2.FileScan.planInputPartitions(FileScan.scala:177)
	at org.apache.spark.sql.execution.datasources.v2.FileScan.planInputPartitions$(FileScan.scala:176)
	at org.apache.kyuubi.spark.connector.hive.read.HiveScan.planInputPartitions(HiveScan.scala:41)`


compared org.apache.spark.sql.execution.datasources.PartitioningAwareFileIndex#listFiles method,  found that the calling method for the PartitionDirectory class has changed in [SPARK-43039] [https://github.com/apache/spark/pull/40677](url)

So is this modification correct?

**Comment by zwq199400** [comment]
> Mind filling in the PR description about which issue you have faced?

pls refer to the comments above

**Comment by pan3793** [comment]
Please provide the component versions and reproducible use cases, this helps the reviewer to evaluate the patch

**Comment by zwq199400** [comment]
> Please provide the component versions and reproducible use cases, this helps the reviewer to evaluate the patch

I found that this bug has been fixed in the v1.9.0, just last month

**Comment by zwq199400** [comment]
> Please provide the component versions(for self complied version, compiling command should be provided too) and reproducible use cases, this helps the reviewer to evaluate the patch

ty for your help

**Pull request closed without merging**
