### PR TITLE
Add more metrics for grafana dashboard

### PR DESCRIPTION
**Pull request by turboFei**
### Why are the changes needed?

Add more metrics for monitoring.

### How was this patch tested?

1. Overall
image2. Connection(repeat for connectionType - `thrift_binary_connection,rest_connection,thrift_http_connection,metadata_request`)
For example:
image
image

image

3. Operation(repeat for operationType - `ExecuteStatement,BatchJobSubmission,LaunchEngine`)

image
image

4. Extra
image

5. Move the JVM statistics down.
### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Comment by pan3793** [comment]
Thanks for making this change, I apply it in Grafana v9.0.8 and it works well.

One suggestion, can we use apply `increase` for `MetadataRequest` panel?
image

**Comment by pan3793** [comment]
btw, I think we should keep the 1m trend interval, "x times per minute" is a very common concept

**Comment by pan3793** [comment]
test failure looks related to #6865

**Comment by pan3793** [comment]
Some JVM panels seem does not work for Java17, which can be fixed later independently.

**Comment by turboFei** [comment]
> Some JVM panels seem does not work for Java17, which can be fixed later independently.

image




> btw, I think we should keep the 1m trend interval, "x times per minute" is a very common concept

Ok

**Comment by turboFei** [comment]
Also add total connections in the overview.
image


@pan3793 It should be almost done.

I will add the `keystore expiration` pannel in next PR.

**Comment by turboFei** [comment]
GC Count for increase instead of total

image

**Comment by turboFei** [comment]
Added keystore expiration:
image

**Comment by turboFei** [comment]
If you select  `ALL` for the `connType` or `opType, it will repeat the rows.
image

**Review by pan3793 — APPROVED** [review]
Verified locally, thanks!

**Comment by pan3793** [comment]
Merged to master

**Pull request closed without merging**
