### PR TITLE
Bump log4j from 2.24.1 to 2.24.2

### PR DESCRIPTION
**Pull request by pionCham**
### Why are the changes needed?
As  @pan3793  pointed out that version 2.24.1 had critical bug in https://github.com/apache/kyuubi/pull/6774#issuecomment-2499523805
Bump bump log4j from 2.24.1 to 2.24.2 
- Release：https://logging.apache.org/log4j/2.x/release-notes.html#release-notes-2-24-2

### How was this patch tested?

GA.

### Was this patch authored or co-authored using generative AI tooling?

No.

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]
LGTM, please fill in the PR template, it's already simplified

**Comment by pan3793** [comment]
Scala 2.13 test failure is irrelevant

**Comment by pionCham** [comment]
> LGTM, please fill in the PR template, it's already simplified

Thanks! I have completed. @pan3793

**Comment by pan3793** [comment]
Thanks, merged to master

**Pull request closed without merging**
