### PR TITLE
Change lock and polling seq_num path on service discovery

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

This PR proposes to change the paths of distributed lock and seq_num(used for POLLING engine pool select policy) on the Service Discovery component. The reason is that namespace `${serverSpace}_${KYUUBI_VERSION}_${shareLevel}_${engineType}/` should be dedicated to engine registration, we'd better use the separated namespace for other functionalities.

- lock path
```
# before
${serverSpace}_${shareLevel}_${engineType}/lock/${user}/${subdomain}

# after
${serverSpace}_${KYUUBI_VERSION}_${shareLevel}_${engineType}_lock/${user}/${subdomain}
```

- seq_num
```
# before
${serverSpace}_${KYUUBI_VERSION}_${shareLevel}_${engineType}/seq_num/${user}/${poolName}

# after
${serverSpace}_${KYUUBI_VERSION}_${shareLevel}_${engineType}_seqNum/${user}/${poolName}
```

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
which the difference between `_xxx/` and `/xxx/` ?

**Comment by pan3793** [comment]
> which the difference between `_xxx/` and `/xxx/` ?

namespace `/abc_xxx/123` is composed of `abc_xxx`, `123`;
namespace `/abc_xxx/123` is composed of `abc`, `xxx`, `123`;

**Comment by pan3793** [comment]
ping @yaooqinn

**Comment by bowenliang123** [comment]
+1

**Comment by pan3793** [comment]
It has been opening for a long time, will merge if no objections before cutting branch-1.7

**Review by cxzl25 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master for 1.7.0

**Pull request closed without merging**
