### PR TITLE
[KYUUBI #5479][AUTHZ] Support Hudi CallProcedureHoodieCommand for stored procedures

### LINKED ISSUE #5479: [Subtask] Support Hudi CallProcedureHoodieCommand
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

Support Hudi CallProcedureHoodieCommand

### Parent issue

#5285 

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### _Why are the changes needed?_
To close #5479 
Support Hudi CallProcedureHoodieCommand,  grammar https://hudi.apache.org/docs/procedures/

- CallProcedureHoodieCommand: https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CallProcedureHoodieCommand.scala

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_
No

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @bowenliang123 @yaooqinn

**Comment by AngersZhuuuu** [comment]
> It's reasonable able to put all the currently supported system procedure in a single list for looping. But what to do for future added procedures, or for the deprecated procedures on some specific versions of Spark or Hudi?

It's ok to list all if we want to support more version. Since each procedure's parameter maybe not same, so need to do like this.

**Comment by bowenliang123** [comment]
SGTM.

**Comment by AngersZhuuuu** [comment]
Any more suggestion?

**Comment by bowenliang123** [comment]
The tests only cover `CALL copy_to_table` and `CALL show_table_properties`. And what about the rest procedures? Will they be covered in follow-ups?

**Comment by AngersZhuuuu** [comment]
> The tests only cover `CALL copy_to_table` and `CALL show_table_properties`. And what about the rest procedures? Will they be covered in follow-ups?

They are almost the same I chose two different types to verify it and for some procedures I have tried it's hard to make it run since it has so many dependencies.

**Comment by bowenliang123** [comment]
SGTM. Maybe subtask issues can be created with `help-wanted` tag if someone else interested in add more tests.

**Review by bowenliang123 — APPROVED** [review]
LGTM. Pending CI tests.

**Comment by AngersZhuuuu** [comment]
> SGTM. Maybe subtask issues can be created with `help-wanted` tag if someone else interested in add more tests.

Yea，also let me check again for the procedure's list.

**Comment by bowenliang123** [comment]
> > SGTM. Maybe subtask issues can be created with `help-wanted` tag if someone else interested in add more tests.
> 
> Yea，also let me check again for the procedure's list.

A similar issue for Iceberg, with all procedures listed. Iceberg procedures face the same situations, as CALL statements are supported and tests required for the rest.

**Comment by AngersZhuuuu** [comment]
> > SGTM. Maybe subtask issues can be created with `help-wanted` tag if someone else interested in add more tests.
> 
> Yea，also let me check again for the procedure's list.

Done cc @bowenliang123

**Comment by pan3793** [comment]
Merged to master

**Pull request closed without merging**
