### PR TITLE
[LICENSE] Update NOTICE

### PR DESCRIPTION
**Pull request by pan3793**
# :mag: Description
## Issue References 🔗

This pull request fixes the NOTICE issue.

## Describe Your Solution 🔧

According to https://infra.apache.org/licensing-howto.html#alv2-dep, we should analyze and bubble up the relevant portions into the top-level NOTICE file, no matter whether they're ASF projects or not.

> If the dependency supplies a NOTICE file, its contents must be analyzed and the relevant portions bubbled up into the top-level NOTICE file.

Kyuubi has some code copied/derived from Apache Iceberg/Hive/Spark/Parquet MR, so we should update NOTICE to respect that.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

Non-code change, review is required.

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by yaooqinn** [comment]
> Kyuubi has some code copied/derived from Apache Iceberg/Hive/Spark/Parquet MR, so we should update NOTICE to respect that.

Please also address these in the LICENSE file.

**Comment by pan3793** [comment]
@yaooqinn listing them under LICENSE is not mandatory, just to facilitate traceability. We already use explicit words like "copied from XXXX" in class comments to achieve that.

**Comment by justinmclean** [comment]
It is best to list the files in LICENSE even if they are ALv2 licensed, as users know which files they are. As all ASFs have the same header files, it is hard to determine where a file comes from, and you may want to update it.

**Comment by pan3793** [comment]
> ... as users know which files they are ...

for project-level auditing, it could be done by searching the keyword "copied from".

for the developer/user reading code, the inline comments are more convenient

image

In my experience, the tracking list maintained externally without an automated script to check is easily out-of-sync, and eventually corrupt.

**Comment by pan3793** [comment]
cc @cfmcgrady you may have the full context of this PR

**Review by cfmcgrady — APPROVED** [review]
LGTM

**Comment by pan3793** [comment]
Thanks, merged to master/1.8/1.7

**Pull request closed without merging**
