### PR TITLE
[DOC] Update logos in layer picture on welcome page

### PR DESCRIPTION
**Pull request by bowenliang123**
# :mag: Description
## Issue References 🔗

This pull request fixes #

## Describe Your Solution 🔧

- update the logos of DBeaver, Mesos and DeltaLake with white background 
- add StarRocks logo to the engine layer
- add Apache Paimon(Incubating) logo to the storage layer
- update JDBC and Python logo on driver layer
- add REST API text on driver layer
- remove outdated SQuirrelSQLClient logo
- fix typo in `etc,` into `etc.,`

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:

image

image

#### Behavior With This Pull Request :tada:

image

image

#### Related Unit Tests

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [ ] Pull request title is okay.
- [ ] No license issues.
- [ ] Milestone correctly set?
- [ ] Test coverage is ok
- [ ] Assignees are selected.
- [ ] Minimum number of approvals
- [ ] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pan3793** [comment]
what's the difference on the dark mode?

**Comment by bowenliang123** [comment]
Seems that there's no dark mode support on our doc website. When I change the system and the Chrome to dark mode, the web pages are still shown in light way.

**Comment by bowenliang123** [comment]
> what's the difference in the dark mode?

It's now outputted with the white background. It's reasonable for this anyway.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
> Seems that there's no dark mode support on our doc website.

Oops, I forgot it.

**Comment by bowenliang123** [comment]
The dark mode could be introduced by merging #5902. But that would draw back the experience of searching with fewer hit texts highlighted on the search result page.

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Pull request closed without merging**
