### PR TITLE
[DO-NOT-MERGE] Flink sql engine compilation on Scala 2.13

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- make Flink SQL Engine module compilable on Scala 2.13
- However, as Flink only provides and is embedded with Scala 2.12 runtime, there's no possible way or gain to use Flink SQL Engine on Scala 2.13.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Simply skipping the flink module should be fine?

**Comment by bowenliang123** [comment]
With this patch, the Flink SQL Engine is compilable on Scala 2.13.
But as Flink only provides and embeds Scala 2.12 runtime inside, there's no possible way or gain to use Flink SQL Engine on Scala 2.13.

I would suggest locking the Scala version to 2.12 in Flink SQL Engine module.
And force to use 2.12 when submitting flink SQL engine, even if using Kyuubi Server on Scala 2.13.

@pan3793 @link3280

**Comment by link3280** [comment]
I think it's a reasonable approach. My concern is that the Flink engine module depends on 2.13 modules like `kyuubi-common`, would that cause compatibility issues?

**Comment by link3280** [comment]
Another approach is to upgrade Flink engine to scala 2.13 anyway. The downside is that we won't be able to use scala expressions or UDFs in Flink engine. It's acceptable because Flink is planning to drop scala support.

**Comment by Yikf** [comment]
If it is confirmed that flink-table-planner_2.12 is not used, then I agree that upgrade Flink engine to scala 2.13 to keep the scala version of all modules is uniform.

**Comment by bowenliang123** [comment]
> I think it's a reasonable approach. My concern is that the Flink engine module depends on 2.13 modules like `kyuubi-common`, would that cause compatibility issues?

It has been proved to cause compatibility issues when running a Flink Engine module compiled with Scala 2.13 on Scala 2.12 runtime which is embedded inside Flink. Either The engine itself or common modules like `kyuubi-common` depends on Scala API implicitly. There are unavoidable breaking changes (e.g alias, collections)between Scala 2.12 and Scala 2.13.

Take the following example, it's caused by the changes in `scala.Serilizable`, as it extends Java's Serilizable in Scala 2.12 while it IS Java's Serilizable in Scala 2.13. 

```
PlanOnlyOperationSuite:
org.apache.kyuubi.engine.flink.operation.PlanOnlyOperationSuite *** ABORTED ***
  java.lang.RuntimeException: Unable to load a Suite class org.apache.kyuubi.engine.flink.operation.PlanOnlyOperationSuite that was discovered in the runpath: java.lang.NoClassDefFoundError: scala/Serializable
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:80)
  at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
  at scala.collection.immutable.Vector1.map(Vector.scala:1872)
  at scala.collection.immutable.Vector1.map(Vector.scala:375)
  at org.scalatest.tools.DiscoverySuite.<init>(DiscoverySuite.scala:37)
  at org.scalatest.tools.Runner$.genDiscoSuites$1(Runner.scala:1131)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1225)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)
  ...
  Cause: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: scala/Serializable
  at org.apache.kyuubi.util.EnumUtils$.isValidEnums(EnumUtils.scala:27)
  at org.apache.kyuubi.config.TypedConfigBuilder.$anonfun$checkValues$2(ConfigBuilder.scala:212)
  at org.apache.kyuubi.config.TypedConfigBuilder.$anonfun$transform$1(ConfigBuilder.scala:170)
```

**Pull request closed without merging**
