### PR TITLE
[KYUUBI #5533][AUTHZ] Support merge into table command for Delta Lake

### LINKED ISSUE #5533: [Subtask] Support merge into table command for Delta Lake
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

Support merge into table command for Delta Lake in Authz plugin.

### Parent issue

#5477 

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by zml1206**
### _Why are the changes needed?_
To close #5533 .
Support merge into table command for Delta Lake.
https://docs.delta.io/latest/delta-update.html#upsert-into-a-table-using-merge

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_
No.

### CODE REVIEW

**Review by bowenliang123 — APPROVED** [review]
LGTM.
The style violation is caused by unchanged Web UI files.

**Review by yaooqinn — APPROVED** [review]

**Comment by bowenliang123** [comment]
Could you rebase onto the latest commit of the master branch? The style check should be then passed.

**Comment by zml1206** [comment]
> Could you rebase onto the latest commit of the master branch? The style check should be then passed.

Done.

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Comment by zml1206** [comment]
Thanks, @bowenliang123 @yaooqinn

**Pull request closed without merging**
