### PR TITLE
[INFRA] Bump github labeler action to v5

### PR DESCRIPTION
**Pull request by panbingkun**
# :mag: Description
## Issue References 🔗

This pull request aims to bump labeler action to v5.

## Describe Your Solution 🔧

The full release notes: https://github.com/actions/labeler/releases/tag/v5.0.0
Version 5 of this action updated the [runtime to Node.js 20](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions). All scripts are now run with Node.js 20 instead of Node.js 16 and are affected by any breaking changes between Node.js 16 and 20.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklists
## 📝 Author Self Checklist

- [ ] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [ ] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [x] Pull request title is okay.
- [x] No license issues.
- [x] Milestone correctly set?
- [ ] Test coverage is ok
- [x] Assignees are selected.
- [x] Minimum number of approvals
- [x] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pan3793** [comment]
cc @bowenliang123 as u tried it previously

**Comment by panbingkun** [comment]
Similar PR has already been done in `Spark repo`: https://github.com/apache/spark/pull/44350

**Comment by bowenliang123** [comment]
image
The CI actions still run on v4. You have to run actions/checkout first to apply the local labler config file.

**Comment by panbingkun** [comment]
> image The CI actions still run on v4. You have to run actions/checkout first to apply the local labler config file.

Manually check as follows:
   1.Considering that the testing of the `github labeler action` is relatively special: When I submitted changes to this repo, the GA still executed the v4 version logic before merging the PR into it
   ref: https://github.com/actions/labeler?tab=readme-ov-file#notes-regarding-pull_request_target, 
   image

  2.I created a similar `private repo` to verify it
  The file (`.github/labeler.yml`) of this private repo is exactly the same as the file I am submitting to Spark repo
  image
  https://github.com/panbingkun/github-action-test/blob/main/.github/labeler.yml

  3.The verification process is as follows:
  A.When I submitted `core/x.scala` to this repo, it automatically labeled `CORE`
   https://github.com/panbingkun/github-action-test/pull/2
   image


   B.When I submitted `core/xxUI. scala` in this library, it automatically labeled `WEBUI`
   https://github.com/panbingkun/github-action-test/pull/3
   image

**Comment by bowenliang123** [comment]
LGTM in changes overall. However external manual validation on a forked Spark repo may not be enough. Last time I reverted similar changes exactly due to assuming things right with skipped validation in PR.

**Comment by pan3793** [comment]
Let's get it in to see what happens. Thanks for your contribution @panbingkun

**Comment by panbingkun** [comment]
> LGTM in changes overall. However external manual validation on a forked Spark repo may not be enough. Last time I reverted similar changes in #5840 and abandoned drafted #5843, exactly due to assuming things right with skipped validation in PR.

After `Spark Merge it`, I verified again whether it is normal, and it is currently normal.
eg: https://github.com/apache/spark/actions/runs/7255705397/job/19766796815?pr=43924
image
If it is not enough, I can verify the exact logic of `` and `` files in `my private repo`

**Comment by pan3793** [comment]
Merged to master, will observe the coming PRs

**Comment by bowenliang123** [comment]
Thanks for your contribution @panbingkun.

**Comment by panbingkun** [comment]
After this merge, I tested one as follows:
https://github.com/apache/kyuubi/pull/5876
At present, it seems normal, 😄

https://github.com/apache/kyuubi/actions/runs/7257083679/job/19770341512?pr=5876
image
image

**Comment by pan3793** [comment]
@panbingkun thanks for the follow-up verification.

**Pull request closed without merging**
