### PR TITLE
[KYUUBI #4916][1.8] Fix Iceberg merge into UT

### PR DESCRIPTION
**Pull request by cxzl25**
### _Why are the changes needed?_

https://github.com/apache/kyuubi/pull/4916#issuecomment-1765708058

https://github.com/apache/kyuubi/actions/runs/6543038657/job/17766954555

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_
No

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks for catching out

**Comment by pan3793** [comment]
please answer the last question in the PR template, it's a kind of requirement for contributors asked by ASF.

> Was this patch authored or co-authored using generative AI tooling?

**Review by bowenliang123 — APPROVED** [review]
Nice catch. This is my mistake here when resolving conflicts for backporting.

**Comment by bowenliang123** [comment]
> please answer the last question in the PR template, it's a kind of requirement for contributors asked by ASF.
> 
> > Was this patch authored or co-authored using generative AI tooling?

Maybe we could change it from the handwritten answer to radio options for YES / NO ?

**Pull request closed without merging**
