### PR TITLE
[KYUUBI #4807][FOLLOWUP] Fix flaky test  "basic batch rest client"

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

Using `eventually` to fix the flaky test.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Please rebase, it was partially fixed by another PR just now

**Comment by bowenliang123** [comment]
This problem is encountered in the real world, which puzzled me.
Compared to repeating more times for consistent local log results, I suggest checking the batch status first and then fetching the local log.

**Comment by turboFei** [comment]
> This problem is encountered in the real world, which puzzled me.
> 
> Compared to repeating more times for consistent local log results, I suggest checking the batch status first and then fetching the local log. Let's see what happens with this approach in #4846 .

It is slow, because we need wait the batch finished.

**Comment by bowenliang123** [comment]
Alright then. LGTM.

**Comment by turboFei** [comment]
thanks, merging to master and 1.7.2

**Pull request closed without merging**
