### PR TITLE
[KYUUBI #4250] Bump Flink to 1.16.1

### LINKED ISSUE #4250: Bump Flink 1.16.1
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

[ANNOUNCE] Apache Flink 1.16.1 released
By Martijn Visser Wed, 01 Feb 2023 11:26:08 -0800

https://www.mail-archive.com/dev@flink.apache.org/msg63739.html

### How should we improve?

_No response_

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by df-Liu**
### _Why are the changes needed?_
close #4250

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by bowenliang123 — APPROVED** [review]

**Review by cxzl25 — APPROVED** [review]

**Comment by bowenliang123** [comment]
`Cannot drop a catalog which is currently in use.`(https://github.com/apache/kyuubi/actions/runs/4125393367/jobs/7135653806#step:6:124)

Switch to the default catalog before dropping catalog `cat_a`.

**Review by bowenliang123 — CHANGES_REQUESTED** [review]
Error: Cannot drop a catalog which is currently in use.(https://github.com/apache/kyuubi/actions/runs/4125393367/jobs/7135653806#step:6:124)

Switch to the default catalog before dropping catalog cat_a.

**Comment by pan3793** [comment]
don't forget to update `.github/workflows/master.yml`

**Comment by bowenliang123** [comment]
This should be better to ship with 1.7 if the problem is fixed. @pan3793

**Comment by pan3793** [comment]
> This PR should be better to ship with 1.7 if the problem is fixed. @pan3793

Yes, updated the milestone.

**Review by bowenliang123 — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]
LGTM, pending CI.

**Review by cxzl25 — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]

**Pull request closed without merging**
