### PR TITLE
[KYUUBI #5253] Upgrade testcontainers-scala from 0.40.12 to 0.41.0

### LINKED ISSUE #5253: Upgrade testcontainers-scala from 0.40.12 to 0.41.0
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Regular Updates

### Artifact Name

https://mvnrepository.com/search?q=testcontainers-scala

### Target Version

0.41.0

### Notable Changes

https://github.com/testcontainers/testcontainers-scala/commits/v0.41.0

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by lsm1**
### _Why are the changes needed?_

close #5253 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_

NO

### CODE REVIEW

**Comment by pan3793** [comment]
Thanks, merged to master/1.8

**Comment by pan3793** [comment]
Sorry, reverted because of breaking changes.

**Review by bowenliang123 — APPROVED** [review]

**Review by pan3793 — APPROVED** [review]

**Comment by lsm1** [comment]
It seems to be some problems, my pr is exclusion org.testcontainers from jetcd-launcher in kyuubi-server pom,but in master branch the change appear in the parent pom, it caused CI failed

**Comment by pan3793** [comment]
https://github.com/apache/kyuubi/pull/5258 is opened to recover CI.

We do exclusion in the parent pom for consistency, except for Hive.

**Comment by lsm1** [comment]
> #5258 is opened to recover CI.
> 
> We do exclusion in the parent pom for consistency, except for Hive.

ok, I see

**Pull request closed without merging**
