### PR TITLE
Bump Commons Lang3 from 3.12.0 to 3.13.0

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- Apache Commons Lang 3.13.0 release note: https://commons.apache.org/proper/commons-lang/changes-report.html#a3.13.0

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_

No.

### CODE REVIEW

**Comment by bowenliang123** [comment]
Commons lang 3.13.0 is the first release in two years since the previous version 3.12.0.

**Review by yaooqinn — APPROVED** [review]

**Review by cxzl25 — APPROVED** [review]

**Comment by bowenliang123** [comment]
Thanks, merged to master (1.8.0).

**Comment by pan3793** [comment]
@bowenliang123 branch-1.8 was cut, don't forget to cherry-pick

**Comment by bowenliang123** [comment]
OK, or let's leave it on the master branch. It's not urgent for backporting to 1.8.0.

**Pull request closed without merging**
