### PR TITLE
Temporarily disable UI Tab for Spark 4.0 and above

### PR DESCRIPTION
**Pull request by pan3793**
# :mag: Description

Spark 4.0 migrated from `javax.servlet` to `jakarta.servlet` in SPARK-47118, which breaks the Kyuubi UI tab.

## Describe Your Solution 🔧

Temporarily disable UI Tab for Spark 4.0 and above.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

Build Kyuubi with Spark 3.5 and successfully launch the Spark engine with Spark 4.0.0 preview1.

image

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by yikf** [comment]
Hi pan, Why does this break the kyuubi ui and is it a known issue with the preview version?

In general, will the kyuubi spark engine tab continue to not support spark 4.0 and above in the future, or will it only be temporary as we now need to test the preview version and this known issue has not yet been fixed?

**Comment by pan3793** [comment]
@yikf This is a temporary workaround, eventually, we may need to introduce a shim layer to dynamically bind to Spark UI classes (`javax.servlet` or `jakarta.servlet`).

**Review by yikf — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master/1.9

**Comment by pan3793** [comment]
Reverted because I have addressed the compatibility issues.

**Pull request closed without merging**
