### PR TITLE
[AUTHZ] Support CreateTableAs command for Paimon

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

Support CreateTableAs command for Paimon
  - Create Table As Command: https://paimon.apache.org/docs/master/engines/spark3/#create-table
  - to validate https://github.com/apache/kyuubi/issues/5470#issuecomment-1787008858

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_

No.

### CODE REVIEW

**Comment by davidyuan1223** [comment]
Look like the test case can success in CI but can not success in local env, could you give some suggests? @pan3793

**Comment by davidyuan1223** [comment]
I want ask a question, why the admin to execute doAs in the next, don't use sql to execute, i found your code is `doAs(admin, createTableAs)`, why not is `doAs(admin,sql(createTableAs))`. 
And i found the DeltaCatalogRanger also use doAs(user,mySql),but the HudiCaralog use doAs(user,sql(mySql)). 
Which is the right way???

@pan3793 could you give some advice

**Comment by davidyuan1223** [comment]
> I want ask a question, why the admin to execute doAs in the next, don't use sql to execute, i found your code is `doAs(admin, createTableAs)`, why not is `doAs(admin,sql(createTableAs))`. And i found the DeltaCatalogRanger also use doAs(user,mySql),but the HudiCatalog use doAs(user,sql(mySql)). Which is the right way???
> 
> @pan3793 could you give some advice

doAs code is
```
  protected def doAs[T](user: String, f: => T): T = {
    UserGroupInformation.createRemoteUser(user).doAs[T](
      new PrivilegedExceptionAction[T] {
        override def run(): T = f
      })
  }
```
If we not use spark.sql to execute our sql, it's only a string format???

**Comment by yaooqinn** [comment]
@davidyuan1223 I believe you are right, and @bowenliang123 made a mistake. Nice catch.

**Comment by davidyuan1223** [comment]
> @davidyuan1223 I believe you are right, and @bowenliang123 made a mistake. Nice catch.

And I found the [DeltaCatalogRanger](https://github.com/apache/kyuubi/blob/master/extensions/spark/kyuubi-spark-authz/src/test/scala/org/apache/kyuubi/plugin/spark/authz/ranger/DeltaCatalogRangerSparkExtensionSuite.scala) also is this code style, I think you need to check the author module's test case to avoid this problem. This problem just like this [comment](https://github.com/apache/kyuubi/issues/5470#issuecomment-1787008858), I want know why admin create table but it can not select from the table?

**Comment by bowenliang123** [comment]
Sorry about that. Will fix and have further investigation.

**Comment by bowenliang123** [comment]
@davidyuan1223 More investigation in the logical plan is required to find the reason. Let me update the test case for Paimon first. And thanks for mentioning possible bug for Delta test suite as well.

**Comment by davidyuan1223** [comment]
> @davidyuan1223 More investigation in the logical plan is required to find the reason. Maybe missing fields in parsed privilege objects. Let me update the test case for Paimon first. And thanks for mentioning possible bug for Delta test suite as well.

thanks your reply, if you find the root cause about this bug, wish you can teach me how to fix this, so that I can complete the issue #5470

**Comment by bowenliang123** [comment]
> > @davidyuan1223 More investigation in the logical plan is required to find the reason. Maybe missing fields in parsed privilege objects. Let me update the test case for Paimon first. And thanks for mentioning possible bug for Delta test suite as well.
> 
> thanks your reply, if you find the root cause about this bug, wish you can teach me how to fix this, so that I can complete the issue #5470

Sure. Will ping you when I came to any conclusion for this. Thanks for creating a bug issue for it.

**Comment by bowenliang123** [comment]
The initial reason is that missing `database`  field in RangerAccessRequest, and the admin user is granted on db-table-column `*-*-*` resource rules.

image

**Comment by davidyuan1223** [comment]
> RangerAccessRequest

LGTM, I will debug in my env

**Comment by davidyuan1223** [comment]
> The initial reason is that missing `database` field in RangerAccessRequest, and the admin user is granted on db-table-column `*-*-*` resource rules.
> 
> image

this is the logic plan about createTableAs, looks like it's plan have some problem
```
CreateTableAsSelect org.apache.paimon.spark.SparkCatalog@4a5f435b, paimon_ns.table2, [provider=PAIMON], true
+- RelationV2[id#6, name#7, city#8] table1
```

**Comment by bowenliang123** [comment]
Yes. Will have a dive-in debugging  in extractors later.

**Comment by bowenliang123** [comment]
Seems that there's a Paimon's `org.apache.paimon.AppendOnlyFileStore` as the Spark Table inside the input query plan, which is unsupported by the DataSourceV2RelationTableExtractor.

image

**Comment by davidyuan1223** [comment]
> Seems that there's a Paimon's `org.apache.paimon.AppendOnlyFileStore` as the Spark Table inside the input query plan, which is unsupported by the DataSourceV2RelationTableExtractor.
> 
> image

looks like the paimon can not supported in kyuubi's authz,? we can not make sure the paimon's plan is same as spark's plan

**Comment by bowenliang123** [comment]
It's normal to see lakehouse has individual implementation of spark plan for some commands. They're still part of spark plans. To support them, we could adapt our extractor for the details of the plan. But the precondition is that table identifier is carried by the plan. Should have look at filestore class of paimon for that.

**Comment by davidyuan1223** [comment]
> It's normal to see lakehouse has individual implementation of spark plan in some commands. They're still part of spark plans. To support them, we could adapt our extractor for the details of the plan. But the precondition is that table identifier is carried by the plan. Should have look at filestore class of paimon for that.

image
The paimon's FileStoreTable top interface's method name is only get the tableName, what can we do to improve the paimon could return database? The source code in 0.5 only will return like `xxx.db/tableName` to tableName

**Pull request closed without merging**
