### PR TITLE
[AUTHZ] Make identifier part name comparision case insenstive in tests of PrivilegeBuilder

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- the identifier parts are turned into lower case by default as `spark.sql.caseSensitive` config  (including catalog, database, table, function name), in [`SessionCatalog.qualifyIdentifier`](https://github.com/apache/spark/pull/37415/files#diff-9dd0899e5406230aeff96654432da54f35255f6dc60eecb87264a5c508a8c826R161) of <https://github.com/apache/spark/pull/37415>
- fix failed ut in Authz pluin tested w/ Spark 3.4
  - AlterTableRenameCommand
  - AlterTableAddPartitionCommand
  - AlterViewAsCommand
  - AlterTableDropPartitionCommand
  - RefreshFunctionCommand
  - AlterTableRenamePartitionCommand
  - AlterTableSetLocationCommand
  - AlterTable(Un)SetPropertiesCommand
  - TruncateTableCommand
  - AlterTableAddColumnsCommand
  - AlterTableChangeColumnCommand
  - ShowCreateTableAsSerdeCommand

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
How far from enabling authz GA w/ Spark 3.4?

**Comment by bowenliang123** [comment]
Still way far from that.

Testing with IcebergTests skipped,

without this PR, 
```
Total number of tests run: 349
Suites: completed 19, aborted 5
Tests: succeeded 269, failed 80, canceled 26, ignored 0, pending 0
*** 5 SUITES ABORTED ***
*** 80 TESTS FAILED ***
```

with this PR,
```
Total number of tests run: 349
Suites: completed 19, aborted 5
Tests: succeeded 297, failed 52, canceled 26, ignored 0, pending 0
*** 5 SUITES ABORTED ***
*** 52 TESTS FAILED ***
```

The failed tests require dive-deep investigation and refactoring/redesigning from result filtering (especially ShowNamesapces for `show tables`), data masking, etc.

**Review by pan3793 — APPROVED** [review]

**Comment by bowenliang123** [comment]
Not happy with the extracted `assertEqualsIgnoreCase` methond in `AssertionUtils`. When assertion fails inside `AssertionUtils`, there's no enough hints for the suite class and the line number. Like,
```
- MergeIntoTable *** FAILED ***
  Expected "[v2jdbctablecatalogprivilegesbuildersuite]", but got "[catalog_ns]" (AssertionUtils.scala:26)
```

**Comment by bowenliang123** [comment]
Now with implicit code position, we are able to trace the assertion where failed:
```
- MergeIntoTable *** FAILED ***
  Expected equaling ignoring case to "local.catalog_ns.catalog_table", but got "catalog_ns" (V2CommandsPrivilegesSuite.scala:459)
```

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Pull request closed without merging**
