### PR TITLE
Change default EC spec to secp521r1 for internal session variable signature

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- change the default EC spec from secp256k1 to secp521r1, as secp256k1 not supported on Java 17

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]
I don't see any risk to change it since it's only used internally

**Review by pan3793 — APPROVED** [review]
I don't see any risk to change it since it's only used internally

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Comment by bowenliang123** [comment]
Docs about “Recommended Curves” in the SunEC Provider
- for Oracle Java 8: https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SunEC
- for Oracle Java 11: https://docs.oracle.com/en/java/javase/11/security/oracle-providers.html#GUID-091BF58C-82AB-4C9C-850F-1660824D5254
- for Oracle Java 17: https://docs.oracle.com/en/java/javase/17/security/oracle-providers.html#GUID-091BF58C-82AB-4C9C-850F-1660824D5254

Curiously, both `secp256k1` and `secp521r1` are on the list.

Not sure whether the same for the temurin, and also wondering why `secp256k1` failed on temurin java 17.
cc @pan3793

**Comment by pan3793** [comment]
secp256k1 failed on Oracle JDK 17.0.4 on my laptop

```
(kyuubi) ➜  apache-kyuubi git:(jdk-17) java -version
java version "17.0.4" 2022-07-19 LTS
Java(TM) SE Runtime Environment (build 17.0.4+11-LTS-179)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4+11-LTS-179, mixed mode, sharing)
```

**Comment by bowenliang123** [comment]
OK, and could you check `secp384r1` and `secp521r1` on Oracle java 17 as well?

**Comment by pan3793** [comment]
`secp384r1` and `secp521r1` are fine

**Pull request closed without merging**
