### PR TITLE
Bump Jersey from 2.36 to 2.38

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

Release notes for Jersey:
- https://github.com/eclipse-ee4j/jersey/releases/tag/2.38
- https://github.com/eclipse-ee4j/jersey/releases/tag/2.37

Changes in this PR:
- `jakarta.activation-api` is now removed from `dependencyList`
- `jakarta.activation-api` added to `kyuubi-kubernetes-it` module's dependency in test scope for satisfying  `hadoop-client-minicluster`

Facts:
- Before : with jersey 2.36,
	- `kyuubi-kubernetes-it` relies on `hadoop-client-minicluster` in test scope
	- `hadoop-client-minicluster` uses `DataSource` and other classes in package `javax.activation` without depending on the depencency
	- `javax.activation` package is actually provied by `jakarta.activation-api` included by `jersey-media-json-jackson`

- Investigation: with jersey 2.38
	- `jakarta.activation-api` was removed in Jersey 2.38 compared to 2.36 (https://github.com/eclipse-ee4j/jersey/compare/2.36...2.38)
	- from the blame history, it's clear that `jakarta.activation-api` was explictly excluded from `jersey-media-json-jackson`
	(https://github.com/eclipse-ee4j/jersey/blob/2.38/media/json-jackson/pom.xml), which in order to apply changes from `maven-enforcer-plugin` in (https://github.com/eclipse-ee4j/jersey/commit/7e7d33928141437fc0448e3f352d513dc2a0ea6d#diff-f47eb7c28b888c017334e057492d4d2eab5be3e0e02bea1ff10765542bf9b9c8R101)

- Solution:
	- added `jakarta.activation-api` to `kyuubi-kubernetes-it` module's dependency in test scope statisfying `hadoop-client-minicluster` 
	- confirm `jakarta.activation-api` is no longer directly or indirectly dependent in maven runtime scope

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
Note:

stay on Jersey 2.x,
- for JAX-RS 2.1 API
- for Java 8+ requirement [since 2.26](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/modules-and-dependencies.html#d0e560), as JDK 11+ required  from 3.1

**Comment by pan3793** [comment]
Could we link the PR which removed the `jakarta.activation-api`?

**Comment by bowenliang123** [comment]
> Could we link the PR which removed the `jakarta.activation-api`?

No commit of Jersey related to the removal of this. I'm also curious about this consequence.
It's more like a shadowed problem. It's assumed that `jakarta.activation-api` is still on the dependency tree.
As ci failed, let me make this PR a draft first.

**Comment by bowenliang123** [comment]
The problem's fixed. And it turns out relatively complicated with misuse and mix-use after investigation.

Conclusion:
- `jakarta.activation-api` is now removed from `dependencyList`
- it's added to `kyuubi-kubernetes-it` module in test scope

Facts:
- Before : with jersey 2.36,
	- `kyuubi-kubernetes-it` relies on `hadoop-client-minicluster` in test scope
	- `hadoop-client-minicluster` uses `DataSource` and other classes in package `javax.activation` without depending on the depencency
	- `javax.activation` package is actually provied by `jakarta.activation-api` included by `jersey-container-servlet-core`  

- Obstocle: with jersey 2.38
	- two ci workflow failed, other tests pass, which are following
		- Spark Engine On Kubernetes Integration Test
		- Kyuubi Server On Kubernetes Integration Test
	- with exception "java.lang.NoClassDefFoundError: javax/activation/DataSource
" (https://github.com/apache/kyuubi/actions/runs/3837070740/jobs/6531967937#step:5:1047)
	- they are both related to `kyuubi-kubernetes-it` module


- Investigation: with jersey 2.38
	- `jakarta.activation-api` was removed in Jersey 2.38 compared to 2.36 (https://github.com/eclipse-ee4j/jersey/compare/2.36...2.38)
	- from the blame history, it's clear that `jakarta.activation-api` was explictly excluded from `jersey-container` pom also impacting `jersey-container-servlet-core`
	(https://github.com/eclipse-ee4j/jersey/blame/d0153ab08819adace8217264ad3ea95651e40396/containers/pom.xml), which in order to apply changes from `maven-enforcer-plugin` in (https://github.com/eclipse-ee4j/jersey/commit/7e7d33928141437fc0448e3f352d513dc2a0ea6d)


- Solution:
	- added `jakarta.activation-api` to `kyuubi-kubernetes-it` module's dependency in test scope statisfying `hadoop-client-minicluster` 
	- confirm `jakarta.activation-api` is no longer directly or indirectly dependent in maven runtime scope


Marks this PR ready for review again.
cc @pan3793

**Comment by pan3793** [comment]
Thanks @bowenliang123, would you mind moving your analysis to the PR description? Then it will be part of the git commit message after PR is merged.

**Review by pan3793 — APPROVED** [review]

**Comment by bowenliang123** [comment]
> Thanks @bowenliang123, would you mind moving your analysis to the PR description? Then it will be part of the git commit message after PR is merged.

OK, the PR description is updated with  essential parts of the analysis.

And I would like to have a followup bumping `jakarta.activation-api` from 1.2.1 to 1.2.2.  It's changing to the dependency name since 1.2.2 from group `javax.activation` to  `jakarta.activation`, although both are published on maven central.

**Comment by pan3793** [comment]
Thanks, merged to master

**Comment by bowenliang123** [comment]
cc @jeanlyn

**Pull request closed without merging**
