### PR TITLE
[SPARK] Improvement for DecimalType serialization in toTColumn for column-based TRowSet generation

### PR DESCRIPTION
**Pull request by bowenliang123**
# :mag: Description
## Issue References 🔗

Subtask of #5808.

## Describe Your Solution 🔧

Improvement for DecimalType serialization in toTColumn for column-based TRowSet generation, by skipping type wrapping inside `HiveResult.toHiveString`.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:
Column-based TRowSet generation with 3000 rows:
`          decimalVal             8.935 ms      335.758 rows/ms`

#### Behavior With This Pull Request :tada:
`          decimalVal             1.135 ms     2643.172 rows/ms`

#### Related Unit Tests
Spark Engine's `RowSetSuite`

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [ ] Pull request title is okay.
- [ ] No license issues.
- [ ] Milestone correctly set?
- [ ] Test coverage is ok
- [ ] Assignees are selected.
- [ ] Minimum number of approvals
- [ ] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by wForget** [comment]
Is this still necessary after #5811 is fixed?

**Comment by bowenliang123** [comment]
I think yes. This is skipping falling through to `RowSet.toHiveString` first, while #5811 is targeted for skipping timeFormatter creation inside `RowSet.toHiveString`.

**Comment by wForget** [comment]
> I think yes. This is skipping falling through to `RowSet.toHiveString` first, while #5811 is targeted for skipping timeFormatter creation inside `RowSet.toHiveString`.

I think this might not be necessary if the RowSet.toHiveString performance issue is fixed since they all just convert decimal to string.

**Comment by bowenliang123** [comment]
> Is this still necessary after #5811 is fixed?

Seems that the answer should be NO.
Reusing the `timeFormatters` for serializing DecimalType gains similar performance improvement. (Screenshot shows reasonable performance even with the DecimalType handling branch commented.)

image

**Comment by bowenliang123** [comment]
Closing this PR with no enough consensus on the purposes, the design, the changes and the approaches.

**Pull request closed without merging**
