### PR TITLE
Fork beeline module from Apache Hive 3.1.3

### PR DESCRIPTION
**Pull request by pan3793**
# :mag: Description
## Issue References 🔗

This is the first step of #6146, to gain a clear commit history, this PR just simply copied the `hive-beeline` module from Apache Hive 3.1.3, with minimal change to pass the tests and manually test basic functionalities, following PRs are going to remove other Hive deps gradually.

## Describe Your Solution 🔧

- Copy source code and test case from Apache Hive 3.1.3
- Drop `org.apache.hive:hive-beeline:3.1.3`
- Backport HIVE-21584 to support JDK 9+
- Drop `HiveCli`, `HiveSchemaTool` and `BeelineInPlaceUpdateStream`, and the corresponding test cases
- Temporary ignore(will fix later) `TestClientCommandHookFactory#testConnectHook` because of error `NoClassDefFound org/apache/curator/RetryPolicy`
- Tune testing code to pass UT

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

Minimal changes to pass the unit tests.

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pan3793** [comment]
Before completing the work, I'd like to collect feedback from the community first.

**Comment by yaooqinn** [comment]
I'm not a fan of fork instead of upstream first. I have no comments. Leave it to others to decide.

**Comment by pan3793** [comment]
The change is almost done, I manually tested some cases locally, and everything went well.

This is the last part to cut Hive deps out from Kyuubi server and client modules.

I'm going to split it to gain a clear changelog history.

**Comment by ulysses-you** [comment]
why fork beeline module can resolve CVE, does those transitive dependencies go away ?

**Comment by pan3793** [comment]
> why fork beeline module can resolve CVE, does those transitive dependencies go away ?

Fork and do minor changes can cut out all Hive's vulnerable deps. To gain a clear git history, those minor changes are planed in follow-up PRs.

**Comment by pan3793** [comment]
@ulysses-you the whole proposal is listed under https://github.com/apache/kyuubi/issues/6146

**Comment by cfmcgrady** [comment]
> Fork and do minor changes can cut out all Hive's vulnerable deps.

+1

**Review by cfmcgrady — APPROVED** [review]

**Review by ulysses-you — APPROVED** [review]
we can go back to upstream once Hive community become active on beeline module

**Review by turboFei — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master

**Pull request closed without merging**
