### PR TITLE
[KYUUBI #6101] Bump Jackson from 2.15.0 to 2.15.4

### PR DESCRIPTION
**Pull request by Deepali1211**
# :mag: Description
## Issue References 🔗

This pull request fixes https://github.com/apache/kyuubi/issues/6101

## Describe Your Solution 🔧

This updates the jackson version from 2.15.0 to 2.15.4

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [X] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pan3793** [comment]
seems there are issues on shading with multi-version artifact, need more investigation

**Comment by Deepali1211** [comment]
@pan3793 All tests have passed now.

**Comment by Deepali1211** [comment]
`[Hive Test (8, -Dhive.archive.mirror=https://archive.apache.org/dist/hive/hive-2.3.9 -Dhive.archiv...](https://github.com/apache/kyuubi/actions/runs/8083005789/job/22085080370?pr=6110#logs)`
This check has failed after running for 6 hrs, could be intermittent.
Do you have option to restart this particular check?

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
The test failure is irrelevant, thanks, merged to master.

**Comment by pan3793** [comment]
@Deepali1211 you may want to link your email `Deepali.gupta@ibm.com` to your GitHub account, otherwise [your contribution](https://github.com/apache/kyuubi/commit/8026e72b3c05532bb4e18b20743ea19113af71a7) won't be counted by GitHub.

**Comment by Deepali1211** [comment]
@pan3793 Thank you for the suggestion. I have linked my personal email Id. Do you mean it has to be org email if they want to count my contributions.

**Comment by pan3793** [comment]
@Deepali1211 there are no restrictions, the email address is extracted from your git commit.

**Comment by Deepali1211** [comment]
Yes, understood the point. Thank you so much!

**Pull request closed without merging**
