### PR TITLE
[KYUUBI #4338] Bump Spark from 3.3.1 to 3.3.2

### LINKED ISSUE #4338: Bump Spark from 3.3.1 to 3.3.2
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Spark 3.3.2 is out.
https://www.mail-archive.com/dev@spark.apache.org/msg29889.html

### How should we improve?

For contributor, please search and replace all places 3.3.1 in codebase

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by a49a**
### _Why are the changes needed?_

close #4338 .

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
Updated the description as `close #4338 .` to make sure it's properly linked to the issue.
image

**Comment by yaooqinn** [comment]
Hi @bowenliang123, that is not necessary if PR has a proper title-prefix

**Comment by bowenliang123** [comment]
> Hi @bowenliang123, that is not necessary if PR has a proper title-prefix

Got that.

**Comment by bowenliang123** [comment]
@a49a Rebase to master branch with https://github.com/apache/kyuubi/pull/4340 merged, to fix docs building error (https://github.com/apache/kyuubi/actions/runs/4191677087/jobs/7266357199#step:4:95).

**Comment by a49a** [comment]
@bowenliang123 I have rebased the master branch. Thank you for your review.

**Comment by pan3793** [comment]
Some Hive Connector tests failed, cc @Yikf

**Comment by Yikf** [comment]
The root cause looks like is `FileWriterFactory#jobId` is not serializable, It was introduced in https://github.com/apache/spark/pull/38980, will take a look.

**Comment by pan3793** [comment]
The failure is resolved by https://github.com/apache/kyuubi/pull/4359, merged to master/1.7

**Pull request closed without merging**
