### PR TITLE
Bump Iceberg to 1.6.1

### PR DESCRIPTION
**Pull request by pionCham**
# :mag: Description
## Issue References 🔗

Apache Iceberg 1.6.1 release https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.6.1

## Describe Your Solution 🔧

In the project POM file, I have updated the Apache Iceberg version from 1.6.0 to 1.6.1

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pionCham** [comment]
cc  @bowenliang123

**Comment by bowenliang123** [comment]
Please update the docs for Spark connector as well, as in #6558.

**Review by bowenliang123 — APPROVED** [review]
LGTM overall.

**Comment by pionCham** [comment]
> Please update the docs for Spark connector as well, as in #6558.

Thanks for pointing out . Done.  @bowenliang123

**Comment by bowenliang123** [comment]
Thanks, merged to master (1.10.0).

**Pull request closed without merging**
