### PR TITLE
[Bug #3302] execute scala code in Kyuubi

### PR DESCRIPTION
**Pull request by zhaohehuhu**
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
will check it at weekends

**Comment by luoyedeyi** [comment]
> will check it at weekends

Any idea for this one?

**Comment by turboFei** [comment]
I have discussed with @cxzl25 .

Seems there is no a appropriate way to prevent the repl class output conflicts.

Because the repl class outputdir is static for exectors.

**Comment by turboFei** [comment]
Also cc @yaooqinn

**Comment by yaooqinn** [comment]
seems there is no workaround for this... it's kind of a JVM restriction.

**Comment by yaooqinn** [comment]
we need a usage guide for scala operation and doc the limitations there, @luoyedeyi would you like to take this?

**Comment by zhaohehuhu** [comment]
> we need a usage guide for scala operation and doc the limitations there, @luoyedeyi would you like to take this?

Yup, I will do that

**Comment by cxzl25** [comment]
Fixed by #4150

**Pull request closed without merging**
