### PR TITLE
[KYUUBI #6704] Disable periodic gc if set interval to 0

### PR DESCRIPTION
**Pull request by taylor12805**
# :mag: Description
## Issue References 🔗

This pull request fixes https://github.com/apache/kyuubi/issues/6704

## Describe Your Solution 🔧

if periodic gc is set to 0, there is no need to perform an explicit gc.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Review by cxzl25 — APPROVED** [review]

**Comment by pan3793** [comment]
behavior change looks good to me, would you mind updating the `doc` of `kyuubi.periodicGC.interval` to mention that?

**Review by bowenliang123 — APPROVED** [review]

**Comment by bowenliang123** [comment]
@taylor12805 Please update the document for `kyuubi.server.periodicGC.interval` in `KyuubiConf` class, and then run `dev/gen/gen_all_config_docs.sh` script to update the markdown docs. Thanks for your contribution.

**Comment by taylor12805** [comment]
> behavior change looks good to me, would you mind updating the `doc` of `kyuubi.periodicGC.interval` to mention that?



> @taylor12805 Please update the document for `kyuubi.server.periodicGC.interval` in `KyuubiConf` class, and then run `dev/gen/gen_all_config_docs.sh` script to update the markdown docs. Thanks for your contribution.

sure, i have updated the document

**Comment by taylor12805** [comment]
> @taylor12805 Please update the document for `kyuubi.server.periodicGC.interval` in `KyuubiConf` class, and then run `dev/gen/gen_all_config_docs.sh` script to update the markdown docs. Thanks for your contribution.

seems like after i executed the script dev/gen/gen_all_config_docs.sh, the modification of document is gone

**Comment by pan3793** [comment]
@taylor12805 you need to modify the code and regenerate the md https://github.com/apache/kyuubi/blob/f8431da7acc4530929ffbddf9fdaa8e6cec9f15c/kyuubi-common/src/main/scala/org/apache/kyuubi/config/KyuubiConf.scala#L3112

**Comment by taylor12805** [comment]
> @taylor12805 you need to modify the code and regenerate the md
> 
> https://github.com/apache/kyuubi/blob/f8431da7acc4530929ffbddf9fdaa8e6cec9f15c/kyuubi-common/src/main/scala/org/apache/kyuubi/config/KyuubiConf.scala#L3112

yeah, sure, i have figured that out

**Review by bowenliang123 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master for 1.10

**Pull request closed without merging**
