### PR TITLE
[KYUUBI #5939] Bump Gluten version to recover Gluten IT

### LINKED ISSUE #5939: [Bug] Gluten-it doesn't seem to be executing as expected
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Gluten project has upgraded the version to 1.2.0-snapshot, but the gluten-it CI still pass. See the log :
https://github.com/apache/kyuubi/actions/runs/7393303592/job/20114021946

We should make sure the tpcds/tpch query plan is transformed.

### Affects Version(s)

master

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by Kwafoor**
# :mag: Description
## Issue References 🔗

This pull request fixes #5939

## Describe Your Solution 🔧

closed #5939 and upgrade gluten version to `1.2.0-SNAPSHOT`
bug fix CI (expected failed): https://github.com/Kwafoor/incubator-kyuubi/actions/runs/7408085340
```
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.apache.kyuubi:kyuubi-gluten-it_2.12:jar:1.9.0-SNAPSHOT: Could not find artifact io.glutenproject:gluten-velox-bundle-spark3.3_2.12-ubuntu_22.04:jar:1.1.0-SNAPSHOT at specified path /home/runner/work/incubator-kyuubi/incubator-kyuubi/integration-tests/kyuubi-gluten-it/../../gluten/package/target/gluten-velox-bundle-spark3.3_2.12-ubuntu_22.04-1.1.0-SNAPSHOT.jar
```
upgrade gluten version `1.2.0-SNAPSHOT` CI succeed:https://github.com/Kwafoor/incubator-kyuubi/actions/runs/7411523117

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Review by ulysses-you — APPROVED** [review]
thank you @Kwafoor , let's see the next nightly CI.

**Comment by pan3793** [comment]
Thanks, merged to master

**Comment by Kwafoor** [comment]
> thank you @Kwafoor , let's see the next nightly CI.

image
gluten cache is right and CI succeed.
https://github.com/apache/kyuubi/actions/runs/7417827262

**Comment by pan3793** [comment]
@Kwafoor thanks for your effort.

**Pull request closed without merging**
