### PR TITLE
[KYUUBI #5832] Always perform closing action in OperationLog to avoid fd leak

### LINKED ISSUE #5832: [Bug] Close KyuubiSession when OperationLog not initialized may lead log file leak
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

I added some debug logs and got the below pictures.
截屏2023-12-08 11 09 01
We can see kyuubi received a close session request and closed corresponding operation logs. Let say thread A done this work. One log was closed before initialized, so the the `OperationLog#close` call did not close writer. 
https://github.com/apache/kyuubi/blob/1d6e65356e6eab6656be6245de89a02e910304ec/kyuubi-common/src/main/scala/org/apache/kyuubi/operation/log/OperationLog.scala#L234-L235
After that, `OperationLog#write` was called by other thread B. Finally, the thread A called `SessionManager#deleteOperationLogSessionDir` and cause log file leak.
截屏2023-12-08 11 15 04

### Affects Version(s)

1.7.1 with #5211 patch

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

Maybe we can delete `if (!initialized) return` to fix it?

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by Flyangz**
# :mag: Description
## Issue References 🔗

This pull request fixes #5832

## Describe Your Solution 🔧

We should always close writer regardless of whether OperationLog is initialized or not, to prevent other threads from continuing to write.

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [x] Pull request title is okay.
- [x] No license issues.
- [x] Milestone correctly set?
- [ ] Test coverage is ok
- [x] Assignees are selected.
- [x] Minimum number of approvals
- [x] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by Flyangz** [comment]
@pan3793 Would you mind reviewing this pr or do you know who can help?

**Comment by bowenliang123** [comment]
LGTM overall.
Could you attach some screenshots as evidence showing the fd leaks properly fixed by this PR? Eg. comparing opened fd numbers, or the server logs.

**Comment by pan3793** [comment]
would you like to try 1.7.3 or 1.8.0? this issue looks like was solved by https://github.com/apache/kyuubi/pull/5211

**Comment by Flyangz** [comment]
> would you like to try 1.7.3 or 1.8.0? this issue looks like was solved by #5211

@pan3793 My online test in issue #5832 had already included this #5211 patch, but the operation logs still leaked.

**Review by pan3793 — APPROVED** [review]
I see your point, the change makes sense to me. would be better to attach your production testing report to prove the patch takes effect as @bowenliang123 suggested.

**Comment by Flyangz** [comment]
Ok, I'll provide it as soon as possible. But I am busy with another more important project recently, and the upgrade of Kyuubi has been stoped. It will probably take a week or two before I can get back to it.

**Review by turboFei — APPROVED** [review]

**Comment by pan3793** [comment]
Anyway, this fix looks good, let me merge it first, looking forward to your testing result once you have time @Flyangz

**Comment by pan3793** [comment]
Merged to master/1.8/1.7

**Pull request closed without merging**
