### PR TITLE
[KYUUBI #4305][Bug] Backport HIVE-15820: comment at the head of beeline -e

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

Backport https://github.com/apache/hive/pull/1814

related kyuubi issues
#4305
#4333 
#4406 

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by turboFei** [comment]
cc @cfmcgrady @cxzl25

**Comment by turboFei** [comment]
cc @lightning-L as well, after this pr, there is no known issue for kyuubi beeline

**Review by cxzl25 — APPROVED** [review]

**Comment by cxzl25** [comment]
also cc @lsm1

**Comment by turboFei** [comment]
thanks, merged to master

**Comment by pan3793** [comment]
backported to 1.7 via eabaee4dfe0e4318f6792e16bbf22479044a17b4

**Pull request closed without merging**
