### PR TITLE
[BUILD] Bump Maven from 3.8.8 to 3.9.9

### PR DESCRIPTION
**Pull request by bowenliang123**
# :mag: Description
## Issue References 🔗

This pull request fixes #

## Describe Your Solution 🔧

- bump Maven from 3.8.x to 3.9.x
- Maven 3.9 release notes:
  - 3.9.0: https://maven.apache.org/docs/3.9.0/release-notes.html
  - 3.9.9: https://maven.apache.org/docs/3.9.9/release-notes.html

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by bowenliang123** [comment]
Other popular projects are now using Maven 3.9, e.g. Spark , and Celeborn.

**Review by yaooqinn — APPROVED** [review]

**Comment by bowenliang123** [comment]
Thanks, merged to master (1.10.0).

**Comment by pan3793** [comment]
Seems we have used a different variable in GitHub workflows to gain the same purpose, it would be great to migrate to the official approch.

https://maven.apache.org/configure.html#maven_args-environment-variable

> `MAVEN_ARGS` environment variable:
>
> Starting with Maven 3.9.0, this variable contains arguments passed to Maven before CLI arguments. E.g., options and goals could be defined with the value `-B -V checkstyle:checkstyle`.

**Comment by bowenliang123** [comment]
> Seems we have used a different variable in GitHub workflows to gain the same purpose, it would be great to migrate to the official approch.
> 
> https://maven.apache.org/configure.html#maven_args-environment-variable
> 
> > `MAVEN_ARGS` environment variable:
> > Starting with Maven 3.9.0, this variable contains arguments passed to Maven before CLI arguments. E.g., options and goals could be defined with the value `-B -V checkstyle:checkstyle`.

Cool. Sounds that `MVN_OPT` custom env var could be replaced by `MAVEN_ARGS` in some way.

**Pull request closed without merging**
