### PR TITLE
[KYUUBI #5438] Add common method to get session level config

### LINKED ISSUE #5438: [TASK][EASY] Add a common getSessionConf method in spark engine module
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/296) and found no similar tasks.

### Mentor

- [X] I have sufficient knowledge and experience of this task, and I volunteer to be the mentor of this task to guide contributors to complete the task.

### Skill requirements

- Knowledge of Kyuubi
- Familiar with the open-source ecosystem

### Background and Goals

As discussed in https://github.com/apache/kyuubi/pull/5410#discussion_r1360164253, some session-level configurations are ignored due to the complexity of get session-level configurations in kyuubi spark engine, so we can implement a common method to get session-level configurations.

### Implementation steps

Add a common method in `org.apache.kyuubi.engine.spark.KyuubiSparkUtil`, like:

```
  def getSessionConf[T](configEntry: ConfigEntry[T], spark: SparkSession): T = {
    spark.conf.getOption(configEntry.key).map(configEntry.valueConverter).getOrElse {
      SparkSQLEngine.kyuubiConf.get(configEntry)
    }
  }
```

Refactor the code that gets configurations using `getSessionConf` method.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by davidyuan1223**
### _Why are the changes needed?_

Current now, in spark-engine module, some session-level configurations are ignored due to the complexity of get session-level configurations in kyuubi spark engine, so As discussed in https://github.com/apache/kyuubi/pull/5410#discussion_r1360164253. If we need unit test use withSessionConf method, we need make the code get configuration from the right session

The PR is unfinished, it need wait the pr https://github.com/apache/kyuubi/pull/5410 success so that i can use the new change in unit test

closes #5438 
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_

No

### CODE REVIEW

**Comment by davidyuan1223** [comment]
@wForget could you review the pr?

**Comment by wForget** [comment]
@davidyuan1223 Can you change this method for more session level configurations.

**Comment by davidyuan1223** [comment]
> @davidyuan1223 Can you change this method for more session level configurations.

ok

**Comment by wForget** [comment]
Most of them like:

```
sparkSession.conf.getOption(XXX)
  .orElse(session.sessionManager.getConf(XXX))
```

**Comment by davidyuan1223** [comment]
> Most of them like:
> 
> ```
> sparkSession.conf.getOption(XXX)
>   .orElse(session.sessionManager.getConf(XXX))
> ```

i have fix this problem, i think 3 session level is enough for this module, they are `SparkConf,SparkSession.KyuubiConf,Kyuubi's Session`, what do you think?

**Comment by wForget** [comment]
> i have fix this problem, i think 3 session level is enough for this module, they are `SparkConf,SparkSession.KyuubiConf,Kyuubi's Session`, what do you think?
 
Sorry, I may not have described it clearly enough. What I mean is changing the way to get the old configurations, not changing this method.

**Comment by wForget** [comment]
BTW, `session.sessionManager.getConf` and `SparkSQLEngine.kyuubiConf` are the same object.

**Comment by davidyuan1223** [comment]
can we merge? @wForget

**Review by wForget — APPROVED** [review]
LGTM, Thanks.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master/1.8

**Pull request closed without merging**
