### PR TITLE
[Arrow] Fix `fallthrough` cases in type conversion and  resultset handling in kyuubi-hive-jdbc

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

Fix possible `fallthrough` cases:
- in DECIMAL_TYPE case of `ArrowUtils#toArrowType`
- in "arrow" case of `KyuubiStatement#executeAsync`

The cases above are discovered from warning from javac output which will be eliminated after this PR:
```
/home/runner/work/kyuubi/kyuubi/kyuubi-hive-jdbc/src/main/java/org/apache/kyuubi/jdbc/hive/KyuubiStatement.java:283: warning: [fallthrough] possible fall-through into case
      default:
      ^
/home/runner/work/kyuubi/kyuubi/kyuubi-hive-jdbc/src/main/java/org/apache/kyuubi/jdbc/hive/arrow/ArrowUtils.java:83: warning: [fallthrough] possible fall-through into case
      case DATE_TYPE:
      ^
```

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
Discovered this minor bug when working on https://github.com/apache/kyuubi/pull/4166.

**Comment by bowenliang123** [comment]
cc @pan3793

**Comment by bowenliang123** [comment]
cc @cfmcgrady

**Review by cfmcgrady — APPROVED** [review]

**Comment by ulysses-you** [comment]
good catch !

**Comment by ulysses-you** [comment]
thanks, merging to master

**Comment by bowenliang123** [comment]
> good catch !

Thx. Warning messages are worth a closer look to seek possible bugs.
And that's why I am cleaning up unhelpful messages in https://github.com/apache/kyuubi/pull/4166.

**Pull request closed without merging**
