### PR TITLE
[KYUUBI #5384][KSCH] Hive connector supports Spark 3.5

### LINKED ISSUE #5384: [TASK][EASY] `kyuubi-spark-connector-hive` supports Spark 3.5
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently the `kyuubi-spark-connector-hive` module is not compatible with spark 3.5.

[kyuubi-spark-connector-hive_compatible_with_Spark_3_5.patch](https://github.com/apache/kyuubi/files/12842411/kyuubi-spark-connector-hive_compatible_with_Spark_3_5.patch)

### Motivation

_No response_

### Describe the solution

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by Kwafoor**
# :mag: Description
## Issue References 🔗

This pull request fixes #5384 

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by Kwafoor** [comment]
For class `FileStatusWithMetadata`, seems not easy to compat with older versions.

**Comment by pan3793** [comment]
are there a lot of breaking changes? is it possible to make it support Spark 3.5 in place?

**Comment by Kwafoor** [comment]
> are there a lot of breaking changes? is it possible to make it support Spark 3.5 in place?

Not a lot, `FileStatusWithMetadata` is a new class in spark 3.5, haven't find the way to compat with older versions.I'll try again.

**Comment by pan3793** [comment]
@Kwafoor please open a new PR to try in-place support first, let's take a look at the specific errors

**Comment by Kwafoor** [comment]
> please open a new PR to try in-place support first

OK, try to support in-place in this PR, if i can't, I will open a new PR.

**Comment by Kwafoor** [comment]
branch name is not correct, does it matter?

**Comment by pan3793** [comment]
> branch name is not correct, does it matter?

it does not matter

**Comment by Kwafoor** [comment]
@wForget @pan3793 Please help me review the code.

**Comment by pan3793** [comment]
@Kwafoor Good job!

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master. This is the last part of full support of Spark 3.5, it's time to change the default Spark version to 3.5

**Pull request closed without merging**
