### PR TITLE
Fix memory leak when using saveToFile

### PR DESCRIPTION
**Pull request by turboFei**
# :mag: Description
## Issue References 🔗

Fix memory leak when using saveToFile mode.

FYI: https://stackoverflow.com/questions/45649044/scala-stream-iterate-and-memory-management

Stream is IterableAgain, which means, that it will keep all the elements you iterate through in case you want to see them again.

## Describe Your Solution 🔧

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by turboFei** [comment]
Similar with https://github.com/apache/kyuubi/pull/3885

**Comment by turboFei** [comment]
cc @wForget

**Review by wForget — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to 1.9.1

**Comment by turboFei** [comment]
also cc @pan3793 It is the second time we meet this issue. we can enhance it later.

**Comment by yaooqinn** [comment]
Late LGTM

**Pull request closed without merging**
