### PR TITLE
Revert Maven to 3.8.7 and Mvnd to 0.9.0

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- to fix connection timeout issue introduced in Maven 3.7

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
The site `downloads.apache.org` removes all the versions of `mvnd` except latest `1.0.0-m6`. And 0.9.0 also not found on `archive.apache.org` site.

**Comment by cfmcgrady** [comment]
> The site `downloads.apache.org` removes all the versions of `mvnd` except latest `1.0.0-m6`. And 0.9.0 also not found on `archive.apache.org` site.

prior to addressing the timeout problem, would it be possible to revert the `mvnd` back to `mvn` in our CI job to rectify the unstable CI job? cc @pan3793 @yaooqinn

**Comment by bowenliang123** [comment]
Closing this as the versions of mvn and mvnd already reverted.

**Comment by bowenliang123** [comment]
Already reverted to mvn. @cfmcgrady

**Pull request closed without merging**
