### PR TITLE
[KYUUBI #5532][AUTHZ] Support Alter table commands of updating table schema for Delta Lake

### LINKED ISSUE #5532: [Subtask] Support Alter table commands of updating table schema for Delta Lake
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

Support alter table command for Delta Lake in Authz plugin.

### Parent issue

#5477 

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by zml1206**
### _Why are the changes needed?_
To close #5532.
Support alter table command for Delta Lake in Authz.
https://docs.delta.io/latest/delta-batch.html#explicitly-update-schema

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_
No.

### CODE REVIEW

**Comment by zml1206** [comment]
cc @bowenliang123

**Review by bowenliang123 — APPROVED** [review]

**Comment by bowenliang123** [comment]
Changed the title into `Support Alter table commands of updating table schema for Delta Lake`, as there are some ALTER commands (e.g. of table properties ) that are still out of coverage.

**Comment by zml1206** [comment]
> Changed the title into `Support Alter table commands of updating table schema for Delta Lake`, as there are some ALTER commands (e.g. of table properties ) that are still out of coverage.

My mistake, I will submit a followup pr later.

**Comment by bowenliang123** [comment]
Never mind, just a typo thing.

**Comment by bowenliang123** [comment]
Thanks, merged to master (1.9.0).

**Comment by zml1206** [comment]
Thanks. @bowenliang123

**Pull request closed without merging**
