### PR TITLE
[FEATURE] [Authz] Support authorization for hive persist function call

### LINKED ISSUE #3632: [FEATURE] [Authz] Support authorization of function usage
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

The spark sql AUTHZ in Kyuubi currently supports authorize create function command , drop function command, and refresh function command.

But the authentication for function usage is not implemented, anyone can use all permanent functions in hive. This behavior needs to be restricted.

### Motivation

_No response_

### Describe the solution

Since function expression may be optimized as constants by catalyst optimization rules, the function usage authorization should be injected before the optimization phase.

So before the optimization rules running, perform the collection of permanent function information involved in the logical plan and construct them as  functionPrivilegeObjects.

I think it's necessary to create a class like RuleAuthorization and inject it as a post-hoc resolution dedicated to the authentication of function usage privileges.

### Additional context

According to the idea of [HIVE-18841](https://issues.apache.org/jira/browse/HIVE-18841), we only need to authenticate the usage of permanent functions, as it doesn't make sense to do usage authorization for temporary functions.

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by packyan**
### _Why are the changes needed?_

to close #3632

The Spark Sql Authz in Kyuubi currently supports authorize create function command , drop function command, and refresh function command.

But the authentication for function usage is not implemented, anyone can use all permanent functions in hive. This behavior needs to be restricted.

Since function expression may be optimized as constants by catalyst optimization rules, the function usage authorization should be injected before the optimization phase.

So before the optimization rules running, perform the collection of permanent function information involved in the LogicalPlan and construct them as functionPrivilegeObjects.

I think it's necessary to create a class like RuleAuthorization and inject it as a post-hoc resolution rule, dedicated to the authentication of function usage privileges.

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by packyan** [comment]
cc @bowenliang123, interested in this feature? Maybe we can collaborate on it.

**Comment by bowenliang123** [comment]
Are you suggesting checking privileges in LogicalPlan in function usage?
Sounds good to have it to diving deep to check details.
Or you could separate the whole job into several subtasks in one umbrella issue and let the community get involved with them.

**Comment by packyan** [comment]
cc @pan3793, @bowenliang123, @yaooqinn

**Comment by bowenliang123** [comment]
@packyan Would you like to adapt the implementation to refactored with Serde layers in Authz as in #4044 ?

**Comment by packyan** [comment]
> @packyan Would you like to adapt the implementation to refactored with Serde layers in Authz as in #4044 ?

Yes, I would working on it with guidance from the Kyuubi community to improve :)

**Comment by bowenliang123** [comment]
Hope to see the reworking soon.

Here's some hints for the new Serde design:
- prevent using magic values of command / function / plan 's name in source code
- define proper spec in package `org.apache.kyuubi.plugin.spark.authz.gen`, and regenerate spec jsons with `JsonSpecFileGenerator`
- expose the extractors via spi through SPI in `resources/META-INF/services`

And also,
- try not to rename the key classes like `RuleAuthorization` if it's not necessary
- small PR is good, and try to separate changes in several PRs

**Comment by packyan** [comment]
> Hope to see the reworking soon.
> 
> Here's some hints for the new Serde design:
> 
> * prevent using magic values of command / function / plan 's name in source code
> * define proper spec in package `org.apache.kyuubi.plugin.spark.authz.gen`, and regenerate spec jsons with `JsonSpecFileGenerator`
> * expose new extractors via SPI in `resources/META-INF/services`
> 
> And also,
> 
> * try not to rename the key classes like `RuleAuthorization` if it's not necessary
> * small PR is good, and try to separate changes in several PRs
> * prevent introduce new dependencies , eg. `spark-hive`, use string and reflection for better compatibility

Thx for your prompt, I plan to divide the whole feature into several subtasks
1. Introduce HiveFunctionPrivilegeBuilder refactored with Serde layers
2. Introduce RuleFunctionAuthorization for persistent function calls authorization
3. Increase test coverage For HiveFunctionPrivilegeBuilder
4. Increase test coverage For RuleFunctionAuthorization

**Comment by bowenliang123** [comment]
Good, you can create an umbrella issue and subtask issues, and the following small PRs.

Also cc @yaooqinn

**Pull request closed without merging**
