### PR TITLE
Fix Trino Status Printer to Prevent Thread Leak

### PR DESCRIPTION
**Pull request by lsm1**
# :mag: Description
## Describe Your Solution 🔧

- use `newDaemonSingleThreadScheduledExecutor` avoid `timer` thread leak
- reduce same status info out

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Review by cxzl25 — APPROVED** [review]

**Comment by lsm1** [comment]
thanks, merged to 1.10.0

**Comment by pan3793** [comment]
@lsm1 if this is a bug fix, consider backporting to maintained versions, currently, branch-1.8 and branch-1.9

**Comment by lsm1** [comment]
> @lsm1* if this is a bug fix, consider backporting to maintained versions, currently, branch-1.8 and branch-1.9

 This bug only exists in version 1.10.0, so backporting is not necessary.

**Comment by pan3793** [comment]
if so, please enrich the PR description to mention the affected version and which commit introduced the bug

**Comment by lsm1** [comment]
> if so, please enrich the PR description to mention the affected version and which commit introduced the bug

ok, done

**Comment by pan3793** [comment]
@lsm1 thanks

**Pull request closed without merging**
