### PR TITLE
[KYUUBI #5952] Disconnect connections without running operations after engine maxlife time graceful period

### LINKED ISSUE #5952: [FEATURE] Disconnect connections without running operations after engine maxlife time graceful period
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

We found that, some kyuubi connections(maybe managed by jdbc connection pool likes hikari) always keep alive, and the engine can not be terminated after exceeds the max life time.

So, we can introduce a graceful period after spark engine max life time, after the graceful period, the connections without running operations will be disconnected forcibly.

### Motivation

_No response_

### Describe the solution

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by turboFei**
# :mag: Description
## Issue References 🔗

We found that, some kyuubi connections(maybe managed by jdbc connection pool likes hikari) always keep alive, and the engine can not be terminated after exceeds the max life time.

So, In this pr, I introduce a graceful period after spark engine max life time, after the graceful period, the connections without running operations will be disconnected forcibly. 

Close #5952

## Describe Your Solution 🔧

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Review by bowenliang123 — APPROVED** [review]

**Comment by cxzl25** [comment]
#2250 has been released for a while, I recommend using a new issue id to track the issue.

**Comment by turboFei** [comment]
Not sure why EtcdConnectionLevelSparkEngineSuite always fail, cc @hddong is there any special for ETCD?

**Comment by wForget** [comment]
> We found that, some kyuubi connections(maybe managed by jdbc connection pool likes hikari) always keep alive, and the engine can not be terminated after exceeds the max life time.

Shall we reject new operations after the engine has stopped gracefully? That way the connection will be closed after session idle timeout.

**Comment by turboFei** [comment]
> Shall we reject new operations after the engine has stopped gracefully? That way the connection will be closed after session idle timeout.

It is difficult to implement in code.

Some rpc does not create operation but will update the session last access time with `withAcquireRelease`.

**Comment by pan3793** [comment]
@turboFei the jetcd upgrade involves gRPC upgrading, I have done it on master, please revert your latest commit and rebase master to see if helps

**Comment by turboFei** [comment]
raised #6020

**Pull request closed without merging**
