### PR TITLE
[KYUUBI #4713][TEST] Fix false positive result in SchedulerPoolSuite

### PR DESCRIPTION
**Pull request by huangzhir**
### _Why are the changes needed?_

fix issuse https://github.com/apache/kyuubi/issues/4713

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [X] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by huangzhir** [comment]
Cause of this issue:
1. threads.shutdown() is asynchronous.
2. When using eventually to judge, if job2 finishes first and job1 has not finished, the value of job1FinishTime is 0. job2FinishTime - job1FinishTime >= 1000 is definitely greater than 0. The main program will exit the eventually method and end the main thread.
3. However, job1 has not produced a result yet, and closing the statement and session will cause an exception.
4. The root cause is that job1 and job2 are executed in multiple threads almost simultaneously, and which one is job1 or job2 is not fixed.

**Review by pan3793 — APPROVED** [review]
Make sense to me, cc @ulysses-you

**Review by ulysses-you — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master/1.7

**Comment by huangzhir** [comment]
hello, @pan3793  There is an error in the code. Can you reopen this PR? This error leads to an obvious failure when checking in the 1.7 branch.

**Review by huangtruman — APPROVED** [review]

**Comment by huangzhir** [comment]
@pan3793 @ulysses-you I've made some changes to the code,make sure job1 started before job2 and would appreciate it if you could review them.

**Review by ulysses-you — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master/1.7

**Pull request merged**
