### PR TITLE
Bump Mockito from 4.9.0 to 4.11.0 and ScalaTest from 3.2.15 to 3.2.16

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- ScalaTest 3.2.16 release note: https://github.com/scalatest/scalatest/releases/tag/release-3.2.16
- ScalaTestPlus plugin 3.2.16 releases plugin for Mockito 4.9.0 or above : https://github.com/scalatest/scalatestplus-mockito/releases/tag/release-3.2.16.0-for-mockito-4.11
- Mockito 4.11.0 is the latest available version of 4.x, which released in Dec 2022 and the last version supporting Java8 : https://github.com/mockito/mockito/releases/tag/v4.11.0

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Review by cfmcgrady — APPROVED** [review]

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Comment by bowenliang123** [comment]
I'm going to revert this change on `scalatest.version` from 3.2.15 to 3.2.16.

Failed to run `mvn clean install -pl :kyuubi-util-scala_2.12` with no meaningful error messages.
```
[INFO] --- resources:3.3.0:testResources (default-testResources) @ kyuubi-util-scala_2.12 ---
[INFO] skip non existing resourceDirectory /Users/bw/dev/kyuubi/kyuubi-util-scala/src/test/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- compiler:3.10.1:testCompile (default-testCompile) @ kyuubi-util-scala_2.12 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/bw/dev/kyuubi/kyuubi-util-scala/target/scala-2.12/test-classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.032 s
[INFO] Finished at: 2023-05-29T17:28:55+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project kyuubi-util-scala_2.12: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by pan3793** [comment]
missing `-a` again? it works well on my side, w/ `-a`

**Comment by bowenliang123** [comment]
Negative.  Run `mvn clean install -pl :kyuubi-util-scala_2.12 -am` and get these errors

```
[INFO] --- scala:4.8.0:testCompile (scala-test-compile-first) @ kyuubi-parent ---
[INFO] compile in 0.0 s
[INFO] No sources to compile
[INFO] 
[INFO] --- scalatest:2.2.0:test (test) @ kyuubi-parent ---
[INFO] ScalaTest report directory: /Users/bw/dev/kyuubi/target/surefire-reports
[WARNING] Output directory does not exist: /Users/bw/dev/kyuubi/target/classes
[WARNING] Test output directory does not exist: /Users/bw/dev/kyuubi/target/test-classes
错误: 找不到或无法加载主类 org.scalatest.tools.Runner
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kyuubi Project Parent 1.8.0-SNAPSHOT:
[INFO] 
[INFO] Kyuubi Project Parent .............................. FAILURE [  1.469 s]
[INFO] Kyuubi Project Util ................................ SKIPPED
[INFO] Kyuubi Project Util Scala .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.716 s
[INFO] Finished at: 2023-05-29T17:34:36+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:2.2.0:test (test) on project kyuubi-parent: Failure because ScalaTest not available on classpath. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by pan3793** [comment]
tested on 3 different machine, M1 macOS, x86 macOS and x86 Linux, everything looks well.

```
build/mvn clean install -pl :kyuubi-util-scala_2.12 -am
```

**Comment by bowenliang123** [comment]
OK, thanks for the validation. After second checks and re-pulling the maven dependency of `org.scalatest`, it is back to successful build on my local machine.

**Pull request closed without merging**
