### PR TITLE
Support ignoring custom app name for Spark engine

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- support to disable custom app name for spark engine, for either share level of USER/GROUP/SERVER. As for CONNECTION share level, custom app name for spark engine is still allowed.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by link3280** [comment]
I'm curious to know why users set the custom app name in the first place if they want the default one?

**Comment by bowenliang123** [comment]
It happened to set a custom spark app name for one time task on the user/client side without notifying the Kyuubi's administrator. Plus, he's using USER / SERVER share level and the app name was contaminated as the one time data task name. From the perspective of Kyuubi's administrator, it's hard to tell it's a shared spark SQL engine on YARN with such custom app name.

Therefore, this feature mainly enables the administrator of Kyuubi and the resource provider, to reject or ignore custom app name with the share level of USER / SERVER / GROUP.

**Comment by link3280** [comment]
@bowenliang123 Thanks for your input! It might apply to Flink as well. Perhaps I should make a related PR for the Flink engine later.

**Comment by bowenliang123** [comment]
No problem, it was a real case in my production environment. It's embarrassinging that our administrator found it difficult to identify the target YARN app of engine instance in the list of mixed app names of MR/Spark/and etc when he was investigating other engine issues.

And let's see how other users interested in this minor feature.

**Comment by pan3793** [comment]
Seems we have `kyuubi.session.conf.ignore.list`, the only difference is it applies to all share levels?

**Comment by bowenliang123** [comment]
Yes. The CONNECTION level should not be limited to custom app name.
And this feature may be extended to combine share level and the customer app name as the final app name, if needed in the future.

**Comment by pan3793** [comment]
How about introducing a `kyuubi.session.conf.sharable.engine.ignore.list`?

**Comment by bowenliang123** [comment]
> How about introducing a `kyuubi.session.conf.sharable.engine.ignore.list`?

It's a considerable approach for this.
It's introducing a new concept `sharable engine` or `sharable share level`. And this config may mix configs for different engine types as well.

**Pull request closed without merging**
