### PR TITLE
[KYUUBI #6043][TEST][GLUTEN] Gluten-it gluten package add arch suffix

### LINKED ISSUE #6043: [Bug] Gluten-it gluten package add arch suffix
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Gluten-it "Gluten Integration TPC-H/DS Test" aciton failed for gluetn#4529([CORE] Add arch suffix for package jar ).

```
Error:  Failed to execute goal on project kyuubi-gluten-it_2.12: Could not resolve dependencies for project org.apache.kyuubi:kyuubi-gluten-it_2.12:jar:1.9.0-SNAPSHOT: Could not find artifact io.glutenproject:gluten-velox-bundle-spark3.3_2.12-ubuntu_22.04:jar:1.2.0-SNAPSHOT at specified path /home/runner/work/incubator-kyuubi/incubator-kyuubi/integration-tests/kyuubi-gluten-it/../../gluten/package/target/gluten-velox-bundle-spark3.3_2.12-ubuntu_22.04-1.2.0-SNAPSHOT.jar -> [Help 1]
```

gluten-velox-bundle-spark3.2_2.12-ubuntu_20.04-1.0.0.jar->gluten-velox-bundle-spark3.2_2.12-ubuntu_20.04_x86_64-1.0.0.jar

### Affects Version(s)

master

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by Kwafoor**
# :mag: Description
## Issue References 🔗

This pull request fixes #6043

## Describe Your Solution 🔧

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by Kwafoor** [comment]
test wf url:https://github.com/Kwafoor/incubator-kyuubi/actions/runs/7825720840

**Comment by Kwafoor** [comment]
Another maven `System Dependencies` is deprecated.Try to use `scalatest-maven-plugin` to add dependency.

**Comment by Kwafoor** [comment]
@ulysses-you @pan3793 cc

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
It's good as a hotfix, merged to master to recover CI first.

**Pull request closed without merging**
