### PR TITLE
[KYUUBI #5362] Remove Spark 3.0 support for Authz

### LINKED ISSUE #5362: [TASK][TRIVIAL] Remove Spark 3.0 support for Authz
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [X] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

Remove test Kyuubi-AuthZ and Spark Test for spark 3.0.3

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### _Why are the changes needed?_
To close #5362 .

Considering the maintenance burden of the Kyuubi community and easy cross-support for data lake projects.
Drop support EOLs of Spark 3 for the coming Spark 4.x era in kyuubi v1.9.
We will still do bugfix release for these spark3.0.x users.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_
No

### CODE REVIEW

**Comment by pan3793** [comment]
It's actually by design to support as many as possible versions of Spark in authz plugin, and support for Spark 3.0 is listed at https://github.com/apache/kyuubi/tree/master/extensions/spark/kyuubi-spark-authz.

BTW, please fill in the PR description seriously, especially answering the "Why are the changes needed?", it's more **important** than "What you changed" for an open-source community.

**Comment by bowenliang123** [comment]
> BTW, please fill in the PR description seriously, especially answering the "Why are the changes needed?", it's more **important** than "What you changed" for an open-source community.

+1. At least try to link to the issue correctly. Metion the issue number with # link prefix in the PR description is the bottom line.

**Comment by yaooqinn** [comment]
It looks OK to me to drop support EOLs of Spark 3 for the coming Spark 4.x era.

**Comment by AngersZhuuuu** [comment]
Conflict fixed

**Comment by bowenliang123** [comment]
Please respect the code of conduct and follow the suggestions in the comments. Update the description properly, please.

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
Hi @bowenliang123 

Considering the maintenance burden of the Kyuubi community and easy cross-support for data lake projects, I guess it's time to remove Spark 3.0 in v1.9.

> Some big companies I know are still using 3.0.x.

As our 1.7 and 1.8 are not EOL, there are still bugfix releases for these users.

**Comment by AngersZhuuuu** [comment]
The failed GA seems not related. cc @yaooqinn

**Comment by bowenliang123** [comment]
> Hi @bowenliang123
> 
> Considering the maintenance burden of the Kyuubi community and easy cross-support for data lake projects, I guess it's time to remove Spark 3.0 in v1.9.
> 
> > Some big companies I know are still using 3.0.x.
> 
> As our 1.7 and 1.8 are not EOL, there are still bugfix releases for these users.

Thanks for the explaination. LGTM if it's decided to describe remove Spark 3.0 as one of the purposes of v 1.9.
Such changes should be disscussed first in the issue rather than in minor comment of PR, in order to  inform the communities.

Once again that I am disappointed with the inadequate level of description in this pull request. I urge all community contributors to understand that all changes require clear explanations of motivation, rationale, and solutions. We should approach all decisions and changes with a responsible attitude, respecting opinions and discussions.

**Comment by AngersZhuuuu** [comment]
Other pr fail GA `CI / Kyuubi Server On Kubernetes Integration Test (pull_request) ` too , should not be related

**Comment by pan3793** [comment]
Thanks @AngersZhuuuu and all, merged to master for 1.9

**Pull request closed without merging**
