### PR TITLE
[KYUUBI #6079] Web UI support Basic authN

### LINKED ISSUE #6079: [TASK][MEDIUM]  Web UI support Basic authN
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

https://github.com/apache/kyuubi/pull/6042#issuecomment-1959437519

### How should we improve?

Support Basic authN for Web UI - that means, when SASL/Plain(LDAP/JDBC/CUSTOM) auth method is configured, pop something like below to allow user login via username and password 

image

### Are you willing to submit PR?

- [x] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by beryllw**
# :mag: Description
## Issue References 🔗

This pull request fixes #6079 

## Describe Your Solution 🔧

image

zpHy0SGauD

image

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Test Plan 🧪

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by beryllw** [comment]
> the frontend code needs to be modified so that all http request will attach a basic auth header

frontend code means web-ui code? 
If user login success, other http request will auto attach a basic auth header.

**Comment by pan3793** [comment]
> If user login success, other http request will auto attach a basic auth header.

interesting, let me verify it locally

**Comment by pan3793** [comment]
found 2 issues:
- if user input the wrong username/password, no way to correct
- only SQL editor works

**Comment by beryllw** [comment]
> * if user input the wrong username/password, no way to correct

Fixing this will change the current authentication logic, i will fix it soon.

> * only SQL editor works

Other api return http status code 405? Because the current user is not an administrator.

```
org.apache.kyuubi.server.api.v1.AdminResource#sessions
    if (!fe.isAdministrator(userName)) {
      throw new NotAllowedException(
        s"$userName is not allowed to list all live sessions")
    }
```

**Comment by pan3793** [comment]
> Other api return http status code 405? Because the current user is not an administrator.

Oh, I see ...

**Comment by beryllw** [comment]
@pan3793 cc

**Comment by pan3793** [comment]
seems a explicitly logout button is required, otherwise user can not switch login user

**Comment by beryllw** [comment]
> seems a explicitly logout button is required, otherwise user can not switch login user


https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication

> What you have to do is have the user click a logout link, and send a ‘401 Unauthorized’ in response, using the same realm and at the same URL folder level as the normal 401 you send requesting a login.

Simple implementation is that when the user clicks the logout button, the server returns 401.

**Comment by pan3793** [comment]
> Simple implementation is that when the user clicks the logout button, the server returns 401.

We can use a specific endpoint for that, so other endpoints behavior won't be affected

**Comment by beryllw** [comment]
> Simple implementation is that when the user clicks the logout button, the server returns 401.

Login users cannot be displayed in this way.Implemented on the frontend code instead.
phoSgHuZKz
mssFmLoEiD

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master/1.9.1

**Pull request closed without merging**
