### PR TITLE
[TEST] Retry more times to fix flaky test "spnego batch rest client"

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- retry more times for `spnego batch rest client` ut of `BatchRestApiSuite`

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
The retry should help. #4719 makes the create batch return early, which increases the chance of this test failure

**Comment by bowenliang123** [comment]
Yes, the tests pass with retries.

**Comment by bowenliang123** [comment]
Let me rebase it and run CI again.

**Comment by pan3793** [comment]
The failures caused by other tests, I think the fix works, is it ready to go?

**Comment by bowenliang123** [comment]
Agree. It's good to go.

**Review by pan3793 — APPROVED** [review]

**Pull request closed without merging**
