### PR TITLE
[KYUUBI #6666][AUTHZ]Upgrade Ranger plugin to 2.5.0

### LINKED ISSUE #6666: [Improvement] Update Spark Ranger plugin to 2.5.0
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Spark AuthZ currently supports Apache Ranger version 2.4.0. Since Apache Ranger has released version 2.5.0, it is essential to update the Spark Ranger plugin to this latest version.

### How should we improve?

_No response_

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by Madhukar525722**
# :mag: Description
## Issue References 🔗

This pull request fixes #6666

## Describe Your Solution 🔧

Bump ranger version to 2.5.0
Release notes: https://cwiki.apache.org/confluence/display/RANGER/Apache+Ranger+2.5.0+-+Release+Notes

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
Can we make the CI happy? Thank you @Madhukar525722

**Comment by Madhukar525722** [comment]
Sure, I will work. Spark tests are failing with

- check ranger policy file *** FAILED ***
  Line 24 is not expected. The file (/home/runner/work/kyuubi/kyuubi/extensions/spark/kyuubi-spark-authz/src/test/resources/sparkSql_hive_jenkins.json) is out of date.  Please regenerate it by running `dev/gen/gen_ranger_policy_json.sh`. Expected "    "[policyItems" : [ {]", but got "    "[conditions" : [ ],]" (PolicyJsonFileGenerator.scala:79)

**Comment by Madhukar525722** [comment]
HI @yaooqinn , CI is smiling. Please review
@bowenliang123 
After running the policy generator and updating the json. The test was failing due to order mismatch. Thats why I have used serialisation.

**Comment by pan3793** [comment]
Thanks, merged to master

**Review by bowenliang123 — COMMENTED** [review]
Late LGTM.

**Pull request closed without merging**
