### PR TITLE
Bump maven from 3.8.6 to 3.6.7

### PR DESCRIPTION
**Pull request by zwangsheng**
### _Why are the changes needed?_

For `maven version` in CI is 3.8.7(get info by adding `/usr/bin/mvn --version` in `.github/workflows/dep.yaml`), 
popo_2023-02-06  09-34-07

We should bump maven version property in parent pom.yaml 3.8.6 => 3.8.7.
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by zwangsheng** [comment]
cc @pan3793 @ulysses-you

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master

**Comment by ulysses-you** [comment]
@zwangsheng  curiously, why does they have different version ? CI also use the cmd: `build/mvn clean install`.

**Comment by pan3793** [comment]
`build/mvn` allows any version equal or greater than the requested version

**Comment by zwangsheng** [comment]
> @zwangsheng curiously, why does they have different version ? CI also use the cmd: build/mvn clean install.
Full log can see more in follow link https://github.com/apache/kyuubi/actions/runs/4082274510/jobs/7036451238,

popo_2023-02-06  09-56-40
Seems using the `cached mvn` instead of `download mvn`

**Comment by ulysses-you** [comment]
ah, I think we should remove that `cache` for the simple dep.yaml workfow to make sure we always use the same maven version with master

**Comment by zwangsheng** [comment]
> ah, I think we should remove that `cache` for the simple dep.yaml workfow to make sure we always use the same maven version with master

+1 for remove cache to ensure we can control maven version, i will make PR for this.

**Comment by pan3793** [comment]
let's change the version check logic in `build/mvn`, it covers more situations

**Comment by cfmcgrady** [comment]
> let's change the version check logic in `build/mvn`, it covers more situations

+1

**Pull request closed without merging**
