### PR TITLE
[DOC] Minor change w/ to with

### PR DESCRIPTION
**Pull request by zhaohehuhu**
### _Why are the changes needed?_

Correct a typo in this doc
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by zhaohehuhu** [comment]
@pan3793  plz help review it

**Review by pan3793 — APPROVED** [review]
LGTM, and w/ is fine too.

**Comment by zhaohehuhu** [comment]
> LGTM, and w/ is fine too.

OK OK. I see there are some "w/"  left.  It's not needed to change anything if so.

**Review by yaooqinn — APPROVED** [review]

**Review by cxzl25 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master

**Pull request closed without merging**
