### PR TITLE
Support authorization on swagger UI

### PR DESCRIPTION
**Pull request by turboFei**
# :mag: Description
## Issue References 🔗

Support authorization on swagger UI.
## Describe Your Solution 🔧

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by turboFei** [comment]
Raised ticket for bearer token authentication: https://github.com/apache/kyuubi/issues/6590

**Review by pan3793 — APPROVED** [review]

**Comment by cfmcgrady** [comment]
I submitted a similar PR to add authorization support for admin resources. https://github.com/apache/kyuubi/pull/4520

**Review by cfmcgrady — APPROVED** [review]
LGTM

**Comment by turboFei** [comment]
thanks, merged to 1.10.0, 1.9.3, 1.8.3

**Pull request closed without merging**
