### PR TITLE
[KYUUBI #4424][REST] Catch No Node Exception, when list kyuubi engines

### LINKED ISSUE #4424: [Bug] [REST] Should cacth `NoNode Exception` instead of throw, when list kyuubi engines
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

When kyuubi server start without submit any engine, zookeeper won't create `engineSpace` node.

When user list kyuubi engines, will face 500 code instead of null.
WX20230227-184422

### Affects Version(s)

master

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by zwangsheng**
### _Why are the changes needed?_

Close #4424 

Catch No Node Exception, when list kyuubi engines

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

WX20230227-184957

### CODE REVIEW

**Comment by ulysses-you** [comment]
Shall we check if engine spec is existed first and return a user-friendly exception ? e.g. `No such engine for user: $user,  engine type: $engineType, share level: $shareLevel, subdomain: $subdomain`

**Comment by zwangsheng** [comment]
> Shall we check if engine spec is existed first and return a user-friendly exception ? e.g. No such engine for user: $user,  engine type: $engineType, share level: $shareLevel, subdomain: $subdomain

This api used for list all engine under namespace or subdomain.

It‘s reasonable if we return an empty list while simple namespace (like `/kyuubi-XXX-version`) not created.

Probably not described clearly in desc, `No Node Exception` is because of the occurrence of kyuubi server namespace node not be created, not engine node not found.

**Comment by zwangsheng** [comment]
@ulysses-you Throw user-friendly exception when namespace node not created.

**Review by ulysses-you — APPROVED** [review]

**Comment by ulysses-you** [comment]
thanks, merging to master

**Pull request closed without merging**
