### PR TITLE
[KYUUBI #5269][Bug] Dupllicated AnalyzesTablesCommand in kyuubi authz

### LINKED ISSUE #5269: [Bug] Dupllicated AnalyzesTablesCommand in kyuubi authz
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

https://github.com/apache/kyuubi/blob/1a69772356f9eccc25d31aa51d4c9b7c6adafe44/extensions/spark/kyuubi-spark-authz/src/main/scala/org/apache/kyuubi/plugin/spark/authz/PrivilegesBuilder.scala#L159-L187

As the code listed above, duplicated `AnalyzeTablesCommand` in authz seems to be an issue, it won't be processed more than one time.

lQLPJwxXbrAm0aDNATLNB76wsMmYIhDggCME7Tui64DSAA_1982_306

additionally, the extractor is incorrect.
 https://github.com/apache/kyuubi/blob/1a69772356f9eccc25d31aa51d4c9b7c6adafe44/extensions/spark/kyuubi-spark-authz/src/main/resources/table_command_spec.json#L912-L921

```
case class AnalyzeTablesCommand(
    databaseName: Option[String],
    noScan: Boolean) extends LeafRunnableCommand {
  ...
}
```

### Affects Version(s)

master

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### _Why are the changes needed?_

To close #5269 .

1.  AnalyzesTablesCommand in table_command_spec  is duplicated and won't be processed
2. The extractor desc of AnalyzesTablesCommand in table_command_spec is wrong

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @pan3793 @yaooqinn

**Comment by bowenliang123** [comment]
Sorry. What is it duplicated with? Further evidence and discussion may be required.
As for now, it's applying to the same plan of analyzing tables in db,  but extracting privilege object for both Databases and Tables.

**Comment by AngersZhuuuu** [comment]
> Sorry. What is it duplicated with? Further evidence and discussion may be required. It seems that they are applied to the same plan of analyzing tables in db, extracting privilege objects for both Databases and Tables.
> 
> It's not consistent in the AnalyzeTablesCommand ut as it only asserts one db-level input object. More improvements here could be made to check table-level objects as it's supposed to do.


First. the extractor is wrong,  second AnalyzeTableCommand won't be proccesed in  table_command_spec

**Comment by bowenliang123** [comment]
Is that are you're reporting for the problem and reason then?
No description. No investigation proof. No detailed purposed solution. And no test running before submitting this PR. And again , no for all without marking this PR as draft.
Are there any similar violated protocols and behaviours in other OSS projects?

**Review by bowenliang123 — CHANGES_REQUESTED** [review]
No clear clue on the purposed fixes.

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
The key concept here is classname of all commands is kinda primary key

**Comment by yaooqinn** [comment]
Hi @AngersZhuuuu AnalyzesTablesCommand shall be removed from java classes, then re-generating the json file.

**Comment by yaooqinn** [comment]
> - check spec json files *** FAILED ***
  Check table_command_spec.json failed. Please regenerate the ranger policy file by running `dev/gen/gen_ranger_spec_json.sh`. generatedStr.equals(existedFileContent) was false (JsonSpecFileGenerator.scala:77)

the test failure is relevant , please update accordingly

**Comment by AngersZhuuuu** [comment]
> > * check spec json files *** FAILED ***
> >   Check table_command_spec.json failed. Please regenerate the ranger policy file by running `dev/gen/gen_ranger_spec_json.sh`. generatedStr.equals(existedFileContent) was false (JsonSpecFileGenerator.scala:77)
> 
> the test failure is relevant , please update accordingly

Updated

**Comment by yaooqinn** [comment]
thanks, merged to master 1.8 and 1.7

**Pull request closed without merging**
