### PR TITLE
[KYUUBI #4712] Bump Spark from 3.2.3 to 3.2.4

### LINKED ISSUE #4712: Upgrade Spark from 3.2.3 to 3.2.4
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Why do we need to upgrade this artifact?

Regular Updates

### Target Version

3.2.4

### Notable Changes

https://spark.apache.org/news/spark-3-2-4-released.html

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by anurag-rajawat**
### _Why are the changes needed?_

Fixes #4712 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]
LGTM, pending CI

**Review by bowenliang123 — APPROVED** [review]

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Comment by packyan** [comment]
@bowenliang123, it seems like you guys merged this PR ?  This commit is wired: https://github.com/apache/kyuubi/commit/93ba8f762f35e5467dbb6cd51ef4e82ba2f74d05

**Comment by bowenliang123** [comment]
Surprised by the commit you've mentioned. I have done the merge for this PR as I reviewed the changed code in this PR and all CI passed. Didn't noticed the commited merge mixed with so much unrelated changed files. Sorry and cc to @pan3793 @anurag-rajawat

**Comment by pan3793** [comment]
Recovered and recommitted in https://github.com/apache/kyuubi/commit/8c7b457d88c97fafd5a4108a282192500ea7cf4e

**Pull request closed without merging**
