### PR TITLE
[KYUUBI #4557][HELM] Kyuubi server should bind Pod IP by default

### LINKED ISSUE #4557: [HELM] Kyuubi server should bind Pod IP by default
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the Helm charts explicitly set Kyuubi server binding to `localhost`, and if user enable HA in the meanwhile, Kyuubi server will register itself to ZK, and that causes the registered address is `localhost:<thrift_port>`.
```
kyuubi.frontend.bind.host=localhost
```

### How should we improve?

Is it possible to dynamically apply the POD IP on launching POD?
```
kyuubi.frontend.bind.host=<POD_IP>
```

Otherwise, we can simply remove `kyuubi.frontend.bind.host` in the template, when absent, Kyuubi server will find the first non-localhost host/ip to bind.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

Fix #4557.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

After changing, the Kyuubi Server correctly binds the Pod IP.
```
KyuubiTBinaryFrontendService#64 - Starting and exposing JDBC connection at: jdbc:hive2://10.88.224.214:10009/
```

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
cc @dnskr @zwangsheng

**Review by zwangsheng — APPROVED** [review]

**Review by cxzl25 — APPROVED** [review]

**Comment by dnskr** [comment]
I've tested it quickly and it doesn't work if I install Kyuubi chart and try to connect from Intellij IDEA using `kubectl port-forward`:
```shell
helm install kyuubi charts/kyuubi
...
kubectl port-forward svc/kyuubi-thrift-binary 10009:10009 -n default
Forwarding from 127.0.0.1:10009 -> 10009
Forwarding from [::1]:10009 -> 10009
Handling connection for 10009
E0320 10:16:55.856000   18444 portforward.go:406] an error occurred forwarding 10009 -> 10009: error forwarding port 10009 to pod 790be50024590075e03f7f0540e464838943ac6ebc370d440836a3de4535f60f, uid : exit status 1: 2023/03/20 09:16:56 socat[8520] E connect(5, AF=2 127.0.0.1:10009, 16): Connection refused
E0320 10:16:55.857032   18444 portforward.go:234] lost connection to pod
```

**Comment by pan3793** [comment]
Do you see the similar log I pasted in the PR description? Does that bind to Pod IP or something else in your case?

**Comment by dnskr** [comment]
Yes, there is IP instead of hostname:
```shell
INFO org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Starting and exposing JDBC connection at: jdbc:hive2://10.244.0.11:10009/
INFO org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient: Created a /kyuubi/serviceUri=10.244.0.11:10009;version=1.7.0;sequence=0000000000 on ZooKeeper for KyuubiServer uri: 10.244.0.11:10009
INFO org.apache.kyuubi.ha.client.KyuubiServiceDiscovery: Service[KyuubiServiceDiscovery] is started.
```

**Comment by pan3793** [comment]
@dnskr I can reproduce the issue, and I have no idea why `kubectl port-forward` does not work. We use ingress in production, and it works well.

@Yikun, do you have any idea why `kubectl port-forward` does not work when the service inside Pod listening Pod IP, but works on listening localhost?

**Comment by Yikun** [comment]
> do you have any idea why kubectl port-forward does not work when the applicaiton inside Pod listening Pod IP, but works on listening localhost?

Not sure, specified address help or not?

```
# all ip
kubectl port-forward svc/kyuubi-thrift-binary --address 0.0.0.0 10009:10009 -n default
# local
kubectl port-forward svc/kyuubi-thrift-binary --address 127.0.0.1 10009:10009 -n default
# your specified ip
kubectl port-forward svc/kyuubi-thrift-binary --address your_ip 10009:10009 -n default
```

**Comment by zwangsheng** [comment]
I reproduce the issue in Mac m1 Minikube Cluster with follow command.
```
helm install kyuubi # with apachekyuubi:1.7.0-spark
```
```log
# Kyuubi Log
2023-03-23 02:40:14.116 INFO org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Starting and exposing JDBC connection at: jdbc:hive2://172.17.0.2:10009/
2023-03-23 02:40:14.153 INFO org.apache.curator.framework.state.ConnectionStateManager: State change: CONNECTED
2023-03-23 02:40:14.202 INFO org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient: Zookeeper client connection state changed to: CONNECTED
2023-03-23 02:40:14.361 INFO org.apache.kyuubi.ha.client.zookeeper.ZookeeperDiscoveryClient: Created a /kyuubi/serviceUri=172.17.0.2:10009;version=1.7.0;sequence=0000000000 on ZooKeeper for KyuubiServer uri: 172.17.0.2:10009
2023-03-23 02:40:14.369 INFO org.apache.kyuubi.ha.client.KyuubiServiceDiscovery: Service[KyuubiServiceDiscovery] is started.
2023-03-23 02:40:14.369 INFO org.apache.kyuubi.server.KyuubiTBinaryFrontendService: Service[KyuubiTBinaryFrontend] is started.
2023-03-23 02:40:14.369 INFO org.apache.kyuubi.server.KyuubiServer: Service[KyuubiServer] is started.
2023-03-23 02:40:14.607 INFO org.apache.kyuubi.Utils: Loading Kyuubi properties from /opt/kyuubi/conf/kyuubi-defaults.con
```
```shell
kubectl port-forward kyuubi-7957995b66-8w4sn 10009:10009

# and start another term run
./bin/beeline -u "jdbc:hive2://127.0.0.1:10009/;#spark.master=local"
```
The port forward occurred
```log
Forwarding from 127.0.0.1:10009 -> 10009
Forwarding from [::1]:10009 -> 10009
Handling connection for 10009
E0323 10:51:18.750107   86266 portforward.go:407] an error occurred forwarding 10009 -> 10009: error forwarding port 10009 to pod e49c1342e3e1a9c0e6c0d6a30d1ba57695be2c77b11820181987a54826bbdf26, uid : exit status 1: 2023/03/23 02:51:17 socat[46240] E connect(5, AF=2 127.0.0.1:10009, 16): Connection refused
E0323 10:51:18.751436   86266 portforward.go:233] lost connection to pod
```

And find some same issue https://github.com/kubernetes/kubectl/issues/1363.
```log
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by pan3793** [comment]
Based on [1], `kubectl port forward` is designed to only support pod/localhost as destination.

So there is an issue for `kubectl port forward`, but considering issue described in #4557, I prefer to get this change in. Anyway, user can set `kyuubi.frontend.bind.host=localhost` in `values.yaml` to address the `kubectl port forward` issue. @dnskr WDYT?

[1] https://atbug.com/how-kubectl-port-forward-works/

**Comment by phyyou** [comment]
@pan3793 Hi, I tested with EKS cluster.

kubectl port-forward (localhost) and k8s service(pod ip) works on `kyuubi.frontend.bind.host=0.0.0.0`

why not use `host = 0.0.0.0`?
```
# parts of my kyuubi defaults in helm chart
        kyuubiDefaults: |
          # Kyuubi configurations https://kyuubi.apache.org/docs/latest/deployment/settings.html
          kyuubi.authentication=NONE
          # kyuubi.engine.share.level=CONNECTION -- Default USER
          kyuubi.metrics.reporters=PROMETHEUS
          kyuubi.frontend.bind.host=0.0.0.0
          kyuubi.frontend.bind.port=10009
          ##################################################
          # Required for k8s and spark CLUSTER mode
          kyuubi.engine.connection.url.use.hostname=false
          kyuubi.frontend.connection.url.use.hostname=false
          kyuubi.session.engine.startup.waitCompletion=true
          ##################################################
 ```

**Comment by pan3793** [comment]
> why not use host = 0.0.0.0?

Then the registered service info becomes `/kyuubi/serviceUri=0.0.0.0:10009;version=1.7.0;sequence=0000000000`, which does not make since

**Comment by dnskr** [comment]
> So there is an issue for `kubectl port forward`, but considering issue described in #4557, I prefer to get this change in. Anyway, user can set `kyuubi.frontend.bind.host=localhost` in `values.yaml` to address the `kubectl port forward` issue. @dnskr WDYT?

Let's go forward and merge the change because `kubectl port-forward` issue has external root cause and should not affect production environments.

**Comment by pan3793** [comment]
Thanks all! Merged to master/1.7

**Comment by phyyou** [comment]
@pan3793 

I think Helm chart notes is wrong from this commit.

https://github.com/apache/kyuubi/blob/dbb741fc5b0d2fd4b0640ff70ea12aca75864166/charts/kyuubi/templates/NOTES.txt#L33-L34

Can we delete this note or if `--address` option is work, then update this note like this? :
```suggestion
 - To access {{ $.Release.Name }}-{{ $name | kebabcase }} service from outside the cluster for debugging, run the following command: 
     kubectl port-forward svc/{{ $.Release.Name }}-{{ $name | kebabcase }} {{ tpl $frontend.service.port $ }}:{{ tpl $frontend.service.port $ }} -n {{ $.Release.Namespace }} --address <your-ip>
```

**Comment by pan3793** [comment]
@phyyou good catch, I forget this place.

Now, the `kubectl port-forward` works when user explicitly defines `kyuubi.frontend.bind.host=localhost` in `values.yaml`, is it easy to write a condition expression in `NOTES.txt`? If yes, we can conditional print it, otherwise I think we can simply delete it.

Would you like to send a follow up PR to update it?

**Comment by pan3793** [comment]
> I think `kyuubiDefaults` option in `values.yaml` is not perfect structure and I can improve it.

Please go ahead, Kyuubi community is open to different thoughts, we appreciate the efforts of all contributors.

**Comment by phyyou** [comment]
Thanks @pan3793.

I went to just too far 😂...
I think it will be just simple improvements.

**Pull request closed without merging**
