### PR TITLE
[KYUUBI #5359] [AUTHZ] Support Create Table Commands for Hudi

### LINKED ISSUE #5359: [Subtask] Support Hoodie Create Command
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

Support Hoodie Create Command

### Parent issue

#5285 

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### _Why are the changes needed?_
To close #5359. Kyuubi authz support hudi create table commands

- [CreateHoodieTableCommand](https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala): https://hudi.apache.org/docs/sql_ddl#create-table
- [CreateHoodieTableAsSelectCommand](https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala): https://hudi.apache.org/docs/sql_ddl#create-table-as-select-ctas
- [CreateHoodieTableLikeCommand](https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableLikeCommand.scala): https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableLikeCommand.scala

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_
No

### CODE REVIEW

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
Hi @AngersZhuuuu, would you please also attach the signatures of these hudi classes in the PR description? Reviewers might have less knowledge about hudi than you. I noticed that it helped me a lot during code review.
For example,

https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala

Also cc @bowenliang123 @packyan @pan3793

**Comment by AngersZhuuuu** [comment]
> Hi @AngersZhuuuu, would you please also attach the signatures of these hudi classes in the PR description? Reviewers might have less knowledge about hudi than you. I noticed that it helped me a lot during code review. For example,
> 
> https://github.com/apache/hudi/blob/master/hudi-spark-datasource/hudi-spark-common/src/main/scala/org/apache/spark/sql/hudi/command/CreateHoodieTableCommand.scala
> 
> Also cc @bowenliang123 @packyan @pan3793

How about current?

**Comment by bowenliang123** [comment]
The pr description is much better now. Thanks for the improvements.

**Comment by pan3793** [comment]
Should the issue be #5359 instead of #5284?

**Comment by AngersZhuuuu** [comment]
> Should the issue be #5359 instead of #5284?

Yea, a copy mistake, changed

**Comment by bowenliang123** [comment]
Please try to link to the issue by adding `#5359` in the description.
GitHub will link this PR to the issue automatically.

**Review by bowenliang123 — APPROVED** [review]
LGTM.

**Comment by pan3793** [comment]
Thanks @AngersZhuuuu and all, merged to master

**Pull request closed without merging**
