### PR TITLE
[CHAT] Make ChatGPT model ID configurable

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- Make ChatGPT model ID configurable

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by bowenliang123** [comment]
According to OpenAI's API reference(https://platform.openai.com/docs/api-reference/completions/create), many detailed settings of chat completion request, other than model id, like `max_tokens`, `topP`,  can be configured.
Do you guys think we should expose them one by one in separate config in Kyuubi , or just expose a config in JSON style, that consumes dynamic settings for ChatGPT? @pan3793 @cxzl25

**Comment by pan3793** [comment]
I would suggest just exposing the most frequently usage small set of the whole parameters.

**Comment by pan3793** [comment]
Please add this PR into the Umbrella task list

**Comment by bowenliang123** [comment]
> I would suggest just exposing the most frequently usage small set of the whole parameters.

Agree. And let's expose parameters on specific purpose.

**Comment by bowenliang123** [comment]
> Please add this PR into the Umbrella task list

Added. Thx for reminder.

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Pull request closed without merging**
