### PR TITLE
[KYUUBI #6281][PY] Add lint rules and action lint checks

### LINKED ISSUE #6281: [TASK][MEDIUM] Setup GitHub Actions for Kyuubi Python client (former PyHive)
### What's the level of this task?

MEDIUM

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before creating

- [X] I have searched in the [task list](https://github.com/orgs/apache/projects/343) and found no similar tasks.

### Mentor

- [ ] I have sufficient expertise on this task, and I volunteer to be a mentor of this task to guide contributors through the task.

### Skill requirements

- GitHub Actions
- Python/Shell scripts
- Hadoop components deployment

### Background and Goals

PyHive has been donated to Apache Kyuubi, the codebase was imported into main repo under `./python`, previously, it used Travis for CI, now, we should migrate the workflow to GitHub Actions.

https://incubator.apache.org/ip-clearance/kyuubi-pyhive.html

### Implementation steps

- Migrate existing CI workflow to GitHub Actions
- Add Spark Thrift Server / Kyuubi to CI workflow

### Additional context

Introduction of [2024H1 Kyuubi Code Contribution Program](https://github.com/apache/kyuubi/issues/6232)

### PR DESCRIPTION
**Pull request by sudohainguyen**
# :mag: Description
## Issue References 🔗

This pull request fixes #6281

## Describe Your Solution 🔧

As part of our efforts to introduce python client built on top of Dropbox's PyHive, I've initialized some linting rules to check with github actions.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:
Code was following flake8 default format which is not sufficient

#### Behavior With This Pull Request :tada:
Lint checks now are powered by ruff

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pan3793** [comment]
I'm not sure we should apply new code-style rules at the current stage, I think we should postpone such things at least after the first release. The most urgent thing is setting up CI to run the python test to ensure our on-going changes won't break the code.

**Comment by sudohainguyen** [comment]
sure we can get back to this PR later

however, I'm facing an authentication error installing CDH and trying docker-compose as another approach

**Comment by pan3793** [comment]
we can use the Apache version for testing.

[this project](https://github.com/awesome-kyuubi/hadoop-testing) may help you to choose the version combination

**Comment by sudohainguyen** [comment]
@pan3793 think we can resume this PR 😄

**Pull request closed without merging**
