### PR TITLE
[KYUUBI #4279] Use new Apache 'closer.lua' syntax for kyuubi-download to obtain engine

### PR DESCRIPTION
**Pull request by sincewhen**
…ne archives

# :mag: Description
## Issue References [4279](https://github.com/apache/kyuubi/issues/4279)🔗

This pull request fixes #

## Describe Your Solution 🔧

Use new Apache 'closer.lua' syntax for kyuubi-download to obtain engine

## Types of changes :bookmark:

- [x] New feature (non-breaking change which adds functionality)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by sincewhen** [comment]
@yaooqinn   please review this PR，thanks

**Comment by yaooqinn** [comment]
Thank you @sincewhen, let's wait and see the test results

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by pan3793** [comment]
The `closer.lua` seems not to work well with the archived package, this causes the CI failure, I am going to revert it to recover CI.

https://github.com/apache/kyuubi/actions/runs/8168780787/job/22331539129?pr=6131

**Comment by sincewhen** [comment]
> The `closer.lua` seems not to work well with the archived package, this causes the CI failure, I am going to revert it to recover CI.
> 
> https://github.com/apache/kyuubi/actions/runs/8168780787/job/22331539129?pr=6131


I see the logs of Flink Test , It seems download  flink release file failer . Howerver，I test it on my compute,it success.
image

**Comment by pan3793** [comment]
does it work for older versions? e.g. Spark 3.3.1 or Flink 1.15.0

**Comment by pan3793** [comment]
For this change itself, unconditionally adding query part `?action=download` to the download URL looks incorrect to me, it may break the usage of custom `spark.archive.mirror` and `spark.archive.name`.

**Pull request closed without merging**
