### PR TITLE
[KYUUBI #5743][AUTHZ] Improve AccessControlException verification of RangerSparkExtensionSuite

### LINKED ISSUE #5743: [Improvement] Make AccessControlException verification of RangerSparkExtensionSuite more rigorous
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

`AssertionUtils.interceptContains` is defective for AccessControlException verification of RangerSparkExtensionSuite. 
For example, the exception message we expect is `does not have [write] privilege on [[$path, $path/]]`, but the actual message is `does not have [write] privilege on [[/tmp/t1, /tmp/ t1/]], [update] privilege on [delta/target]`, 
The current implementation is undetectable.

### How should we improve?

Add and use new function `AssertionUtils.interceptEndswith`.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by zml1206**
# :mag: Description
## Issue References 🔗

This pull request fixes #5743.

## Describe Your Solution 🔧

Add and use new function AssertionUtils.interceptEndswith.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests
Exists test cases.

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [x] Pull request title is okay.
- [x] No license issues.
- [x] Milestone correctly set?
- [x] Test coverage is ok
- [x] Assignees are selected.
- [x] Minimum number of approvals
- [x] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by zml1206** [comment]
The exception messages of many suites are incomplete. I will resubmit them multiple times according to different stored suites.

**Comment by zml1206** [comment]
Delta Lake: #5747

**Comment by yaooqinn** [comment]
Hi @zml1206, could you please assist in getting the CI to turn green? Thank you.

**Comment by zml1206** [comment]
> Hi @zml1206, could you please assist in getting the CI to turn green? Thank you.

Of course, I will deal with it later.

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master

**Comment by zml1206** [comment]
Thanks, @yaooqinn

**Pull request closed without merging**
