### PR TITLE
[KYUUBI #6726] Support trino stage progress

### PR DESCRIPTION
**Pull request by taylor12805**
# :mag: Description
## Issue References 🔗

This pull request fixes https://github.com/apache/kyuubi/issues/6726

## Describe Your Solution 🔧

Add trino statement progress 

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by lsm1** [comment]
@taylor12805 Before submitting the pull request, we can use ./dev/reformat to format the code.

**Comment by lsm1** [comment]
> > @taylor12805*  Before submitting the pull request, we can use ./dev/reformat to format the code.
> 
> @lsm1* thanks for reminding. I added test case for trino statement progress, however since trino don't have sleep function, I can't mock multiple stages case. Do you have some ideas?

Adding a sleep function in Trino is not straightforward, so simple unit tests should be sufficient for now.

**Review by yaooqinn — APPROVED** [review]

**Review by cxzl25 — APPROVED** [review]

**Comment by lsm1** [comment]
@taylor12805  Please fix the failing test

```
- get operation progress *** FAILED ***
  The code passed to eventually never returned normally. Attempted 1623 times over 25.002736579 seconds. Last failure message: Expected List("Stage-0 ........", "FINISHED", "5", "5", "0", "0", "0", ""), but got Buffer("Stage-0 ........", "FINISHED", "3", "3", "0", "0", "0", ""). (TrinoOperationProgressSuite.scala:43)
 ```

**Comment by pan3793** [comment]
unfortunately, this patch fails the scala 2.13 CI, @taylor12805 could you please fix that?

**Pull request closed without merging**
