### PR TITLE
[KYUUBI #6564] Insert into table check the privilege of table

### LINKED ISSUE #6564: [AUTHZ][Improvement] insert into table should check the update privilege for table
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, Authz will check check the update privilege for the column of the table. I think it is better to check the update privilege for the table.
```
insert into test values(1);
user [xxx] does not have [update] privilege on [database=testdb/table=test/column=id]
```

### How should we improve?

check the update privilege for the table.

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by liujiayi771**
# :mag: Description
## Issue References 🔗

This pull request fixes #6564

## Describe Your Solution 🔧

Remove the `columnDesc` for `InsertIntoHadoopFsRelationCommand ` and `InsertIntoHiveTable ` in `table_command_spec.json`

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:
Insert into table will check the privilege of columns.

#### Behavior With This Pull Request :tada:
Insert into table will check the privilege of table.

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by liujiayi771** [comment]
@pan3793 Could you help to review?

**Review by pan3793 — APPROVED** [review]
make sense to me

**Review by AngersZhuuuu — APPROVED** [review]
Nice catch!

**Comment by pan3793** [comment]
Thanks, merged to master/1.9.3/1.8.3

**Pull request closed without merging**
