### PR TITLE
Format the kyuubi-ctl batch command output

### PR DESCRIPTION
**Pull request by turboFei**
# :mag: Description
## Issue References 🔗

As title, format the batch command output.
## Describe Your Solution 🔧

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by wForget** [comment]
Related style error:

```
Error: ] /home/runner/work/kyuubi/kyuubi/kyuubi-ctl/src/main/scala/org/apache/kyuubi/ctl/cmd/submit/SubmitBatchCommand.scala:20: Unused import
```

**Comment by turboFei** [comment]
spotless can not resolve the `unused import` issue for scala.

Should we involve a script `lint-scala` to check the scala style fast?

@wForget @pan3793

**Comment by wForget** [comment]
> Should we involve a script lint-scala to check the scala style fast?

Sounds good to me.

**Review by wForget — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to 1.10.0/1.9.3

**Pull request closed without merging**
