### PR TITLE
[BUILD] Skip compiling useless files when making distribution

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

To speed up the making distribution.

Refer https://github.com/apache/spark/pull/41141

This PR add more skip properties when making distribution:

- -Dmaven.javadoc.skip=true to skip generating javadoc
- -Dmaven.scaladoc.skip=true to skip generating scaladoc. Please see: https://davidb.github.io/scala-maven-plugin/doc-jar-mojo.html#skip
- -Dmaven.source.skip to skip generating sources.jar

### _How was this patch tested?_
Manual test:
image

```
 ./build/dist --spark-provided --hive-provided --flink-provided
```

Before this pr:
```
[INFO] Total time:  09:20 min
```

After this pr:
```
[INFO] Total time:  06:46 min
```

### CODE REVIEW

**Comment by cfmcgrady** [comment]
I think it's safe to skip building the test jar when making distribution.

**Comment by pan3793** [comment]
> I think it's safe to skip building the test jar when making distribution.

Maybe work, please try on a clean machine, or change the version before running dist.

**Comment by cfmcgrady** [comment]
> > I think it's safe to skip building the test jar when making distribution.
> 
> Maybe work, please try on a clean machine, or change the version before running dist.

it's unsafe since the module `Kyuubi Spark TPC-DS Connector` required the dependency `org.apache.kyuubi:kyuubi-spark-connector-common_2.12:jar:tests:1.8.0.1:test`


```
onnector-tpcds_2.12:jar:1.8.0.1: Could not find artifact org.apache.kyuubi:kyuubi-spark-connector-common_2.12:jar:tests:1.8.0.1 in gcs-maven-central-mirror (https://maven-central-asia.storage-download.googleapis.com/maven2/) -> [Help 1]
```

**Review by cfmcgrady — APPROVED** [review]

**Review by bowenliang123 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master

**Pull request closed without merging**
