### PR TITLE
Pin threeten 1.7.0

### PR DESCRIPTION
**Pull request by pan3793**
### _Why are the changes needed?_

Pin `org.threeten:threeten-extra:1.7.0` for spark master as a workaround for https://github.com/ThreeTen/threeten-extra/issues/226

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Review by bowenliang123 — APPROVED** [review]
LGTM

**Comment by bowenliang123** [comment]
Title => Pin Threeten 1.7.0 in Spark 3.4?

**Comment by pan3793** [comment]
Thanks, merged to master, let's wait for the daily CI result.

**Comment by bowenliang123** [comment]
Let's revisit this PR and check again when Spark 3.4 is released.

**Pull request closed without merging**
