### PR TITLE
[KYUUBI #6411] Grpc common support

### LINKED ISSUE #6411: [Subtask] Add new module common-grpc to support more grpc server in the future
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

Add new module common-grpc for compatible with more grpc engine

### Parent issue

#6324

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by davidyuan1223**
# :mag: Description
## Issue References 🔗

This pull request fixes #6411

## Describe Your Solution 🔧

Add a common module common-grpc to support grpc type fronendservice/backendservice, which can compitable with another grpc engine, not only spark connect

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by ulysses-you** [comment]
Thank you @davidyuan1223 , I think we should make the first commit goal clear. Custom grpc things do not help us support Spark connect (the key make ExecutePlanRequest to be compatible with Kyuubi ?). I think we can add a test: use Spark connect client to query/cancel on a Kyuubi grpc server.

**Comment by davidyuan1223** [comment]
> Thank you @davidyuan1223 , I think we should make the first commit goal clear. Custom grpc things do not help us support Spark connect (the key make ExecutePlanRequest to be compatible with Kyuubi ?). I think we can add a test: use Spark connect client to query/cancel on a Kyuubi grpc server.

You are right, I will add a test case to test spark connect client with kyuubi server

**Comment by ulysses-you** [comment]
@davidyuan1223 thank you for the work. Do you require this patch https://github.com/apache/spark/pull/45775 ?

This issue is due to connect required a higher guava version which is different with Spark core itself, but connect depends on the Spark core's shaded guava.

I think this issue has been fixed in Spark3.5.2 which is on RCing, we can use the 3.5.2 rc version to verify it and change to use 3.5.2 after released.

**Comment by davidyuan1223** [comment]
> @davidyuan1223 thank you for the work. Do you require this patch [apache/spark#45775](https://github.com/apache/spark/pull/45775) ?
> 
> This issue is due to connect required a higher guava version which is different with Spark core itself, but connect depends on the Spark core's shaded guava.
> 
> I think this issue has been fixed in Spark3.5.2 which is on RCing, we can use the 3.5.2 rc version to verify it and change to use 3.5.2 after released.

thanks, i will try!  The spark-connect package has troubled me for a long time. Its proto classes conflict with connect-common, forcing me to shade it. Then I encountered a problem with Guava, and despite trying many methods, it still didn't work.

**Comment by ulysses-you** [comment]
thank you @davidyuan1223 , if you find any other issues related to Spark, just craete PR to Spark community. We can help review and push it.

**Pull request closed without merging**
