### PR TITLE
[KYUUBI #4611] support all sessions api in SessionRestApi

### LINKED ISSUE #4611: [Subtask] SessionRestApi support all api in SessionsResources
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

support all api in SessionsResources in SessionRestApi

### Parent issue

https://github.com/apache/kyuubi/issues/4602

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by lightning-L**
### _Why are the changes needed?_

Close #4611 

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by lightning-L** [comment]
@turboFei

**Comment by turboFei** [comment]
```
SessionsResourceSuite:
- open/close and count session
- getSessionList
- get session event *** FAILED ***
  javax.ws.rs.ProcessingException: Error reading entity from input stream.
  at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:934)
  at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:853)
  at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:298)
  at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:93)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
  at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
  at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:244)
  at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:90)
  ...
  Cause: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "clientIp" (class org.apache.kyuubi.events.KyuubiSessionEvent), not marked as ignorable (17 known properties: "sessionName", "conf", "eventTime", "endTime", "serverIP", "user", "clientVersion", "startTime", "sessionType", "sessionId", "clientIP", "eventType", "openedTime", "engineId", "remoteSessionId", "exception", "totalOperations"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 533] (through reference chain: org.apache.kyuubi.events.KyuubiSessionEvent["clientIp"])
```

**Review by turboFei — APPROVED** [review]
LGTM

**Review by turboFei — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to master

**Pull request closed without merging**
