### PR TITLE
Fix broken link in `kerberos.rst`

### PR DESCRIPTION
**Pull request by Yikf**
### _Why are the changes needed?_

Fix broken link in `kerberos.rst`

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by Yikf** [comment]
Before:
image
After:
image

**Comment by pan3793** [comment]
@Yikf please don't forget to update the milestone after merging.

**Comment by pan3793** [comment]
cherry-picked to 1.7

**Comment by Yikf** [comment]
@pan3793 Ok, sorry for that

**Pull request closed without merging**
