### PR TITLE
Support PUT method in REST client

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

We have api that need `PUT` method.
image

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
should the docs you reference be `delete` ?

**Comment by turboFei** [comment]
> should the docs you reference be delete ?

now the supported actions are `close` or `cancel`.

But I think that maybe we can support more actions. so, `put` should be better.

**Review by bowenliang123 — APPROVED** [review]
LGTM. PUT requests are idempotent and can be used for different purposes.

**Comment by ulysses-you** [comment]
I'm fine with this, as it's a reserved client api to be compatible with future server feature.

**Review by pan3793 — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to master

**Pull request closed without merging**
