### PR TITLE
Use G1GC as Java option example in kyuubi-env template

### PR DESCRIPTION
**Pull request by bowenliang123**
# :mag: Description
## Issue References 🔗

As described.

## Describe Your Solution 🔧

G1 garbage collector is supported in Java 8+ and has become  the default garbage collector in Java 17+.
Use G1GC to simplify JVM options example in kyuubi-env for KYUUBI_JAVA_OPTS and KYUUBI_BEELINE_OPTS, and for better production deployment usage of higher Java version users out of box.

- use G1 for garbage collector
- Remove CMS and ParNew related options
- Use UseGCOverheadLimit option
- Use UseStringDeduplication option for G1GC
- Reorder options in resources, GC mechanism, GC printing/logging

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:
No behavior change.

#### Behavior With This Pull Request :tada:
Uncomment the template and use the suggested default JVM options for starting Kyuubi server.

image

#### Related Unit Tests
CI test. Tested starting Kyuubi server locally.

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [x] Pull request title is okay.
- [x] No license issues.
- [x] Milestone correctly set?
- [x] Test coverage is ok
- [x] Assignees are selected.
- [x] Minimum number of approvals
- [x] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by yaooqinn** [comment]
Instead of changing CMS to G1 in examples.

How about writing a tuning guide in docs? FYI, https://spark.apache.org/docs/latest/tuning.html#garbage-collection-tuning

**Comment by bowenliang123** [comment]
Changing CMS to G1 in examples is necessary, considering many users may use examples out of the box for deployment. G1 works fine with Java 8+.

As for the GC tuning guide, we could do it later. Unlike Spark as a computing engine, Kyuubi's tuning guide should be more focused in comprehensive resource control, including threads, memory and related metrics.

**Comment by yaooqinn** [comment]
OK, thanks.
BTW -- For now, fulfilling the PR description checklist is a required step.

**Comment by bowenliang123** [comment]
> OK, thanks. BTW -- For now, fulfilling the PR description checklist is a required step.

Sure.
I have already described the changes in detail in the PR descriptsion and reviewed the Author Self Checklist, by ticking the appropriate options. Is that sufficient? Or should the Committer Pre-Merge Checklist also be checked and ticked by the submitter?

**Comment by yaooqinn** [comment]
It would be great if you could provide the Test Plan by verifying the related bash scripts locally.

**Comment by bowenliang123** [comment]
Updated the test plan and the screenshot for using Java options as suggested in the template.
Could you have a check on it?  @yaooqinn

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master

**Pull request closed without merging**
