### PR TITLE
[KYUUBI #6574] Skip eagerly execute command in PlanOnly mode of Spark Engine

### LINKED ISSUE #6574: [FEATURE] Skip eagerly execute command in PlanOnly mode of Spark Engine
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Currently command may be executed eagerly in physical/execution PlanOnly mode of Spark Engine, we should avoid this behavior.

### Motivation

_No response_

### Describe the solution

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by wForget**
# :mag: Description
## Issue References 🔗

This pull request fixes #6574

## Describe Your Solution 🔧

Skip eagerly execute command in physical and execution plan only mode

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

added unit test

---

# Checklist 📝

- [X] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by ulysses-you** [comment]
I know we have dropped support Spark3.1, but this pr would make it fail to compile with Spark3.1 and previous. I just post this issue and I'm fine if it is acceptable for the community.

**Comment by wForget** [comment]
> I know we have dropped support Spark3.1, but this pr would make it fail to compile with Spark3.1 and previous. I just post this issue and I'm fine if it is acceptable for the community.

Some incompatibilities with spark 3.1 have been introduced since #6273

**Comment by pan3793** [comment]
branch-1.9 still works for Spark 3.1, if this is only target to master, it is fine to break 3.1

**Review by ulysses-you — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master

**Pull request closed without merging**
