### PR TITLE
[WIP] Feat aws provider

### LINKED ISSUE #4118: [FEATURE] Support aws iam for authentiction / authorization
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the feature

Provide a way for users to :
- get access to data based on their users IAM roles
- login thought access token, id/secret or other IAM stuff

### Motivation

currently AFAIK, only user/password and kerberos are provided

### Describe the solution

kyuubi itself could have a role which could assume other role. For a given user, kyuubi could check if the role it provided as jdbc parameter can be assumed and passed to the engine (spark supports IAM roles)

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by parisni**
### _Why are the changes needed?_

This allows to deal with aws iam author. The idea is to make the kyuubi jdbc driver able to inject iam stuff. The aws sdk dependencies have been added. Multiple awsProvider will be implemented:

-  [ ] default chain provider
- [x] sso (integration tests made manually)
- [ ] basic auth (access/secret)
- [ ] assumed roles
 
Fixes #4118 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
Hey @parisni, can we switch the target branch to the default?

**Comment by parisni** [comment]
> Why is there such a big gap between 1.6 and 1.7? I noticed that your new code change has little relevance to the old ones.
well when I compile the jdbc-driver 1.7 I am not able to deal with 1.6 kyuubi server. 

> FYI, the client libs are about to be transferred to https://github.com/apache/kyuubi-client repo
Then this PR will be transfered to kyuubi-client since the implementation is only on client side, which convert jdbc variables/config into relevant spark conf

**Comment by parisni** [comment]
in the current proposal, all takes place on the jdbc-drivern side. 
Since only the client has the aws iam knowledge to access the aws
ressources. 
Then the driver only acts as an intermediary layer, with no action but
passing
the configs to the engine.

We may move the configuration builder (spark.hadoop.s3a...) on the
server side, and make it possible 
to support multiple engine. Thought ?

**Comment by yaooqinn** [comment]
> well when I compile the jdbc-driver 1.7 I am not able to deal with 1.6 kyuubi server. 

Can you take a look at this? @pan3793 @turboFei 

Sorry for being late @parisni, it was Spring Festival in China for the past 2 weeks

**Comment by turboFei** [comment]
> well when I compile the jdbc-driver 1.7 I am not able to deal with 1.6 kyuubi server.

Could you provide the error message? @parisni

**Pull request closed without merging**
