### PR TITLE
[KYUUBI #4305][Bug] Backport HIVE-15820: comment at the head of beeline -e

### PR DESCRIPTION
**Pull request by lsm1**
### _Why are the changes needed?_

close [#4305](https://github.com/apache/kyuubi/issues/4305)

### manual tests

```sql
bin/beeline -u jdbc:hive2://X:10009 -e "
--asd
select 1 as a
"
```

image

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [x] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
Can you add some unit tests?

**Comment by bowenliang123** [comment]
How about ut for multi single-line comments? 
`"--comment line 1 \n    --comment line 2 \n show database;"`

**Review by bowenliang123 — APPROVED** [review]

**Comment by bowenliang123** [comment]
Run `dev/reformat` to fix the code style violations.

**Comment by pan3793** [comment]
@cfmcgrady would you please check will this change breaks the pyspark case?

**Comment by cfmcgrady** [comment]
> @cfmcgrady would you please check will this change breaks the pyspark case?

I think this should be a breaking change to run python snippets. I will check when I have time.

**Comment by cfmcgrady** [comment]
test run multi-line python snippets with this change.

```
0: jdbc:hive2://192.168.206.48:10009/> for i in [1, 2, 3]:
. . . . . . . . . . . . . . . . . . .>     print(i);
2023-02-16 17:00:50.824 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing anonymous's query[1215c099-cf9a-4c42-80c1-5290a456b8ea]: PENDING_STATE -> RUNNING_STATE, statement:
for i in [1, 2, 3]:
    print(i)
23/02/16 17:00:50 INFO ExecutePython: Processing anonymous's query[fdc19881-4918-47f3-8b39-c1e97d01269b]: PENDING_STATE -> RUNNING_STATE, statement:
for i in [1, 2, 3]:
    print(i)
23/02/16 17:00:50 INFO ExecutePython:
           Spark application name: kyuubi_USER_SPARK_SQL_anonymous_default_a5f44f5d-d3ec-49e1-a594-8b0460e9728d
                 application ID: local-1676537993814
                 application web UI: http://192.168.206.48:65528
                 master: local[*]
                 deploy mode: client
                 version: 3.3.1
           Start time: 2023-02-16T16:59:50.066
           User: anonymous
23/02/16 17:00:50 INFO ExecutePython: Processing anonymous's query[fdc19881-4918-47f3-8b39-c1e97d01269b]: RUNNING_STATE -> FINISHED_STATE, time taken: 0.002 seconds
2023-02-16 17:00:50.836 INFO org.apache.kyuubi.operation.ExecuteStatement: Query[1215c099-cf9a-4c42-80c1-5290a456b8ea] in FINISHED_STATE
2023-02-16 17:00:50.836 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing anonymous's query[1215c099-cf9a-4c42-80c1-5290a456b8ea]: RUNNING_STATE -> FINISHED_STATE, time taken: 0.011 seconds
+---------+---------+--------+---------+------------+
| output  | status  | ename  | evalue  | traceback  |
+---------+---------+--------+---------+------------+
| 1
2
3   | ok      |        |         | []         |
+---------+---------+--------+---------+------------+
1 row selected (0.06 seconds)
```

**Comment by cfmcgrady** [comment]
thanks, merging to master(v1.8.0)/branch-1.7(v1.7.0)/branch-1.6(v1.6.2)

**Comment by cfmcgrady** [comment]
sorry for wrongly locally testing before, this is a breaking change for submitting multi-line python snippets.


<details>
<summary>log</summary>

```
0: jdbc:hive2://192.168.205.128:10009/> for i in [1, 2, 3]:
. . . . . . . . . . . . . . . . . . . >     print(i);
2023-02-23 17:26:12.280 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing anonymous's query[d70621de-5a0b-4253-8f3f-a4c51cacc806]: PENDING_STATE -> RUNNING_STATE, statement:
for i in [1, 2, 3]:
print(i)
23/02/23 17:26:13 INFO ExecutePython: Processing anonymous's query[209c8f29-3e06-4ce6-9271-f2ce396741ba]: PENDING_STATE -> RUNNING_STATE, statement:
for i in [1, 2, 3]:
print(i)
23/02/23 17:26:13 INFO ExecutePython:
           Spark application name: kyuubi_USER_SPARK_SQL_anonymous_default_f7512afe-f0b3-449e-bf45-164af364616b
                 application ID: local-1677144339509
                 application web UI: http://192.168.205.128:59896
                 master: local[*]
                 deploy mode: client
                 version: 3.3.1
           Start time: 2023-02-23T17:25:37.933
           User: anonymous
23/02/23 17:26:13 INFO DAGScheduler: Asked to cancel job group 209c8f29-3e06-4ce6-9271-f2ce396741ba
23/02/23 17:26:13 ERROR ExecutePython: Error operating ExecutePython: org.apache.kyuubi.KyuubiSQLException: Interpret error:
for i in [1, 2, 3]:
print(i)
 Some(PythonResponse(execute_reply,PythonResponseContent(null,IndentationError,expected an indented block (<stdin>, line 2),List(  File "<stdin>", line 2
,     print(i)
,         ^
, IndentationError: expected an indented block
),error)))
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.$anonfun$executePython$1(ExecutePython.scala:96)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.withLocalProperties(ExecutePython.scala:160)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.org$apache$kyuubi$engine$spark$operation$ExecutePython$$executePython(ExecutePython.scala:81)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$$anon$1.run(ExecutePython.scala:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

org.apache.kyuubi.KyuubiSQLException: Interpret error:
for i in [1, 2, 3]:
print(i)
 Some(PythonResponse(execute_reply,PythonResponseContent(null,IndentationError,expected an indented block (<stdin>, line 2),List(  File "<stdin>", line 2
,     print(i)
,         ^
, IndentationError: expected an indented block
),error)))
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.$anonfun$executePython$1(ExecutePython.scala:96)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.withLocalProperties(ExecutePython.scala:160)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.org$apache$kyuubi$engine$spark$operation$ExecutePython$$executePython(ExecutePython.scala:81)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$$anon$1.run(ExecutePython.scala:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
23/02/23 17:26:13 INFO ExecutePython: Processing anonymous's query[209c8f29-3e06-4ce6-9271-f2ce396741ba]: RUNNING_STATE -> ERROR_STATE, time taken: 0.01 seconds
2023-02-23 17:26:13.096 INFO org.apache.kyuubi.operation.ExecuteStatement: Query[d70621de-5a0b-4253-8f3f-a4c51cacc806] in ERROR_STATE
2023-02-23 17:26:13.103 INFO org.apache.kyuubi.operation.ExecuteStatement: Processing anonymous's query[d70621de-5a0b-4253-8f3f-a4c51cacc806]: RUNNING_STATE -> ERROR_STATE, time taken: 0.823 seconds
Error: org.apache.kyuubi.KyuubiSQLException: org.apache.kyuubi.KyuubiSQLException: Error operating ExecutePython: org.apache.kyuubi.KyuubiSQLException: Interpret error:
for i in [1, 2, 3]:
print(i)
 Some(PythonResponse(execute_reply,PythonResponseContent(null,IndentationError,expected an indented block (<stdin>, line 2),List(  File "<stdin>", line 2
,     print(i)
,         ^
, IndentationError: expected an indented block
),error)))
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.$anonfun$executePython$1(ExecutePython.scala:96)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.withLocalProperties(ExecutePython.scala:160)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.org$apache$kyuubi$engine$spark$operation$ExecutePython$$executePython(ExecutePython.scala:81)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$$anon$1.run(ExecutePython.scala:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.spark.operation.SparkOperation$$anonfun$onError$1.applyOrElse(SparkOperation.scala:188)
        at org.apache.kyuubi.engine.spark.operation.SparkOperation$$anonfun$onError$1.applyOrElse(SparkOperation.scala:172)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.$anonfun$executePython$1(ExecutePython.scala:99)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.withLocalProperties(ExecutePython.scala:160)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.org$apache$kyuubi$engine$spark$operation$ExecutePython$$executePython(ExecutePython.scala:81)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython$$anon$1.run(ExecutePython.scala:111)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kyuubi.KyuubiSQLException: Interpret error:
for i in [1, 2, 3]:
print(i)
 Some(PythonResponse(execute_reply,PythonResponseContent(null,IndentationError,expected an indented block (<stdin>, line 2),List(  File "<stdin>", line 2
,     print(i)
,         ^
, IndentationError: expected an indented block
),error)))
        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.engine.spark.operation.ExecutePython.$anonfun$executePython$1(ExecutePython.scala:96)
        ... 9 more

        at org.apache.kyuubi.KyuubiSQLException$.apply(KyuubiSQLException.scala:69)
        at org.apache.kyuubi.operation.ExecuteStatement.waitStatementComplete(ExecuteStatement.scala:129)
        at org.apache.kyuubi.operation.ExecuteStatement.$anonfun$runInternal$1(ExecuteStatement.scala:161)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748) (state=,code=0)

```
</details>

**Comment by pan3793** [comment]
@cfmcgrady, any solution? we should revert it if we can not fix it properly

**Comment by cfmcgrady** [comment]
> @cfmcgrady, any solution? we should revert it if we can not fix it properly

I don't have any thoughts on this issue, maybe we should revert it first?

**Comment by cxzl25** [comment]
> sorry for wrongly locally testing before, this is a breaking change for submitting multi-line python snippets.

We can add this python UT later?

**Pull request closed without merging**
