### PR TITLE
[KYUUBI #3926][FOLLOWUP] Supplement LICENSE-binary

### PR DESCRIPTION
**Pull request by Yikf**
### _Why are the changes needed?_

This pr is followup of the https://github.com/apache/kyuubi/pull/3944, it supplement LICENSE-binary

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by Yikf** [comment]
cc @pan3793

**Review by pan3793 — CHANGES_REQUESTED** [review]
Please

- Copy the license text file to licenses/
- Append content into NOTICE-binary content if antlr provides NOTICE

**Review by pan3793 — APPROVED** [review]

**Comment by Yikf** [comment]
@pan3793 Hi, have other suggestions? This PR is ready to merge

**Comment by bowenliang123** [comment]
Any possible link to the original version of antlr's BSD license source?

**Comment by Yikf** [comment]
> Any possible link to the original version of antlr's BSD license source?

https://github.com/antlr/antlr4/blob/master/LICENSE.txt

**Review by bowenliang123 — APPROVED** [review]

**Comment by Yikf** [comment]
Thanks all, merged to master

**Pull request closed without merging**
