### PR TITLE
[KYUUBI #6541] [AUTHZ] Fix DataSourceV2RelationTableExtractor can't get the 'database' attribute if it's a Paimon plan.

### LINKED ISSUE #6541: [AUTHZ] Check previleges for Paimon
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### Describe the bug

Before this PR, If Spark-ranger is enabled, the Paimon query will be rejected, because the corresponding dbname cannot be obtained when the plan is parsed.
when the **select xx from pamion.db.table** commond is executed.
The DataSourceV2Relation#table in org.apache.paimon.spark.SparkTable, The 'database' value could not be obtained, ranger need this parameter during verification.
image

### Affects Version(s)

1.9.1

### Kyuubi Server Log Output

_No response_

### Kyuubi Engine Log Output

_No response_

### Kyuubi Server Configurations

_No response_

### Kyuubi Engine Configurations

_No response_

### Additional context

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to fix.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by promising-forever**
# :mag: Description
## Issue References 🔗

This pull request fixes #6541

## Describe Your Solution 🔧
Fix an issue where DataSourceV2RelationTableExtractor#table could not fetch the ‘database’ attribute causing the Ranger checks to fail when using the Paimon Catalog.
If the database attribute is not resolved, use DataSourceV2RelationTableExtractor#identifier to complete it.

## Types of changes :bookmark:

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Related Unit Tests

---

# Checklist 📝

- [ ] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

**Be nice. Be informative.**

### CODE REVIEW

**Comment by promising-forever** [comment]
plz help review @pan3793 . Thanks very much.😄

**Comment by pan3793** [comment]
the fix makes sense to me, but scala 2.13 failure is related, please fix it. cc @bowenliang123

**Comment by bowenliang123** [comment]
LGTM overall.

**Comment by promising-forever** [comment]
> the fix makes sense to me, but scala 2.13 failure is related, please fix it. cc @bowenliang123

I know why the compilation fails and I will fix it.

**Comment by promising-forever** [comment]
> > the fix makes sense to me, but scala 2.13 failure is related, please fix it. cc @bowenliang123
> 
> I know why the compilation fails and I will fix it.

Fixed scala 2.13 compilation failures.
I'm not sure why [CI / Flink Test (8, 1.18, normal) (pull_request)] is failing, but it doesn't seem to be related to this PR.

**Review by bowenliang123 — APPROVED** [review]
LGTM. All the spark tests passed. Feel free to promote Authz plugin to more Paimon cases. Thanks.

**Comment by bowenliang123** [comment]
Thanks for the contribution. Merged to master(1.10.0) and branch-1.9 (1.9.3).

**Comment by promising-forever** [comment]
> LGTM. All the spark tests passed. Feel free to promote Authz plugin to more Paimon cases. Thanks.

I will make the time to complete this task.

**Pull request closed without merging**
