### PR TITLE
[INFRA] Separate the steps for build and test for Spark CI jobs

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

For fast-failing with the errors in compilation and builds, separate the steps for build and testing for Spark, the same way as in `Flink Test` and `Hive Test`. Separated steps also help to find exception messages in very long logging output, which could be up to around 3k lines, in sections.

image

### _How was this patch tested?_
CI actions pass.

### CODE REVIEW

**Comment by bowenliang123** [comment]
Do you have any idea for the failures in the testing step after separation? @pan3793

**Comment by pan3793** [comment]
I guess the separation will extend the whole time for the positive cases, the compiling error should be easy to catch locally.

**Comment by bowenliang123** [comment]
The whole time should not be expanded in much added time.
As `mvn install` should have properly compiled and installed the latest jar's in the local repo, `mvn test` just use all the compiled source and tests from local.

**Comment by bowenliang123** [comment]
The current obstacle is why `mvn test` just failed to lookup compiled classes after `mvn install -DskipTests`?
https://github.com/apache/kyuubi/actions/runs/3963918607/jobs/6792291190#step:7:547
```
Error: ] /home/runner/work/kyuubi/kyuubi/externals/kyuubi-spark-sql-engine/src/test/scala/org/apache/kyuubi/engine/spark/operation/PySparkTests.scala:28: object KyuubiHiveDriver is not a member of package org.apache.kyuubi.jdbc
Error: ] /home/runner/work/kyuubi/kyuubi/externals/kyuubi-spark-sql-engine/src/test/scala/org/apache/kyuubi/engine/spark/operation/PySparkTests.scala:29: object hive is not a member of package org.apache.kyuubi.jdbc
Error: ] /home/runner/work/kyuubi/kyuubi/externals/kyuubi-spark-sql-engine/src/test/scala/org/apache/kyuubi/engine/spark/operation/PySparkTests.scala:70: not found: type KyuubiHiveDriver
```

**Pull request closed without merging**
