### PR TITLE
Add organization info in Maven pom

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- Add the organization node in Maven pom file, following the instructions: https://maven.apache.org/pom.html#organization

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_

No.

### CODE REVIEW

**Comment by bowenliang123** [comment]
The organization info is identical to Spark's, see https://github.com/apache/spark/blob/6b1ff22dde1ead51cbf370be6e48a802daae58b6/pom.xml#L46

**Review by yaooqinn — APPROVED** [review]

**Comment by pan3793** [comment]
Seems already existed in `org.apache:apache:pom`

**Comment by bowenliang123** [comment]
> Seems already existed in `org.apache:apache:pom`

Yes, thanks for mentioning that.
Spark does the same, as it extends `org.apache:apache:pom` and also declares the organization again.
https://github.com/apache/spark/blob/6b1ff22dde1ead51cbf370be6e48a802daae58b6/pom.xml#L46

**Comment by bowenliang123** [comment]
Closing this PR. Spark seems an exception that has a dedicate organization declaration in pom.

**Pull request closed without merging**
