### PR TITLE
[DRAFT] increase compiler heap size for ci jobs

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- increase compiler heap size for ci jobs, to see whether it helps to speed up build time

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
Increasing memory size (to 4GB) contributes to build time reduction , but not much.
Build time seems more rely on the utility rate of the host machine.
But I think still good to do this, what do you think?
cc @cfmcgrady @pan3793

**Comment by pan3793** [comment]
I prefer to keep as-is if there is no meaningful gain.

**Comment by bowenliang123** [comment]
OK. Closing this PR.

**Comment by cfmcgrady** [comment]
I doubt that this configuration really works? at least, it does not work on my local build. We need to change the max heap size in the script `build/mvn` instead of `pom.xml`.

**Comment by bowenliang123** [comment]
I changed the MAVEN_OPTS in ci jobs which will be used in `build/mvn` in this line.

```
export MAVEN_OPTS=${MAVEN_OPTS:-"$_COMPILE_JVM_OPTS"}
```

**Comment by cfmcgrady** [comment]
I mean change `-Xmx2g` to `-Xmx4g`, not the configuration of the plugin `maven-compiler-plugin`, it does not work on my local build.

https://github.com/apache/kyuubi/blob/7cd206642c962b233a86edfe17f0bb0c99e34c70/build/mvnd#L25

**Pull request closed without merging**
