### PR TITLE
[KYUUBI 4715] [AUTHZ] Fix the incorrect class name of InsertIntoHiveDirCommand in table spec generator

### LINKED ISSUE #4715: [Improvement] [AUTHZ] Spec json files should be auto generated, rather than edit manually
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

In #4658, this pr edit the [table_command_spec.json](https://github.com/apache/kyuubi/pull/4660/files#diff-9e9de8073ec13128987f6c7e163f71696771bebb96442ed5808642e2c8453cec), but this file should be generated by JsonSpecFileGenerator.scala, rather than edited this file manually.

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by packyan**
### _Why are the changes needed?_

to close #4715 

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
You can referer this PR to change to one-time generator to test suite for check generated golden files.
https://github.com/apache/kyuubi/pull/4677/files#diff-30f8af2f8dfb17df96d4b4da322723a1baf0f9ae5171faa29f23e40206ea9e51R57

**Comment by packyan** [comment]
> You can referer this PR to change to one-time generator to test suite for check generated golden files.
> 
> #4677 
> 
> 
> 
> https://github.com/apache/kyuubi/pull/4677/files#diff-30f8af2f8dfb17df96d4b4da322723a1baf0f9ae5171faa29f23e40206ea9e51R57

Sounds good, I will reference this RP and add a UT for check generated golden files.

But can we merge this bug fix firstly?

**Comment by packyan** [comment]
> Alright, but is there any clue why we have to change the name of the plan in the generator rather than just change the generated files?
> 
> 

In my case, when I was developing function privileges build feature, I needed to use the generator to regenerate spec json files. I trusted the results generated by the generator without checking whether the json had been manually modified.  This caused my pr to fail in CI.  Although directly modifying the generated json has no effect on users, it is not friendly to developers.

**Comment by bowenliang123** [comment]
@packyan Can I have an offline discussion with you for further details? Are you in one of Wechat discussion group？

**Comment by bowenliang123** [comment]
Let's fix the inconsistency in the spec json file in this PR first. And move the regeneration and validation to #4717.

**Review by bowenliang123 — APPROVED** [review]
LGTM.

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Pull request closed without merging**
