### PR TITLE
[TEST] Add RowFilteringTestBase to improve the test coverage

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

Add RowFilteringTestBase to improve the test coverage

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @bowenliang123 

BTW, can you take a look at the mvnd failure?

```
Error: Exception in thread "main" org.mvndaemon.mvnd.common.DaemonException$StaleAddressException: Could not receive a message from the daemon.
Daemon id: 83189804
```

**Comment by bowenliang123** [comment]
> cc @bowenliang123
> 
> BTW, can you take a look at the mvnd failure?
> 
> ```
> Error: Exception in thread "main" org.mvndaemon.mvnd.common.DaemonException$StaleAddressException: Could not receive a message from the daemon.
> Daemon id: 83189804
> ```

Let's rerun the failed job this time. It seems mvnd daemon crashes due to memory usage or concurrency. Will consider increasing `mvnd.maxHeapSize` and lower the concurrency.

**Comment by yaooqinn** [comment]
I tried serval times but consistently failed

**Comment by bowenliang123** [comment]
> I tried serval times but consistently failed

Yes, I noticed. But curiously the same job for other PR passes.
How about merge this PR without style check this time.

**Review by bowenliang123 — APPROVED** [review]
LGTM.

**Comment by pan3793** [comment]
Thanks, merged to master

**Pull request closed without merging**
