### PR TITLE
[KYUUBI #5529][AUTHZ][FOLLOWUP] Remove useless org.apache.spark.sql.delta.commands.CreateDeltaTableCommand

### LINKED ISSUE #5529: [Subtask] Support create table command for Delta Lake
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues) and found no similar issues.

### Describe the subtask

Support create table command for Delta Lake in Authz plugin.

### Parent issue

#5477

### Are you willing to submit PR?

- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by zml1206**
### _Why are the changes needed?_
To close #5529 .
Remove useless `org.apache.spark.sql.delta.commands.CreateDeltaTableCommand`.

Because the logical plans for Delta Lake create table and replace table are `org.apache.spark.sql.catalyst.plans.logical.CreateTable`, `org.apache.spark.sql.catalyst.plans.logical.CreateV2Table` and `org.apache.spark.sql.catalyst.plans.logical.ReplaceTable`.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_
No.

### CODE REVIEW

**Comment by zml1206** [comment]
cc @pan3793

**Comment by yaooqinn** [comment]
1. is CreateDeltaTableCommand for the old versions of delta?
2. Do we still have tests for create delta tables?

**Comment by zml1206** [comment]
`CreateDeltaTableCommand` is only used by `org.apache.spark.sql.execution.datasources.v2.CreateTableExec`,  `org.apache.spark.sql.execution.datasources.v2.ReplaceTableExec` and `org.apache.spark.sql.execution.datasources.v2.CreateTableAsSelectExec`. So Create Delta Table Command is only used for plan of `CreateTable`, `ReplaceTable` and `CreateTableAsSelect`.

**Review by yaooqinn — APPROVED** [review]

**Review by cfmcgrady — APPROVED** [review]
LGTM

**Comment by cfmcgrady** [comment]
thanks, merging to master(v1.9.0).

**Comment by zml1206** [comment]
Thanks @yaooqinn @cfmcgrady

**Pull request closed without merging**
