### PR TITLE
[WIP][KYUUBI #5337] Added Custom Audit Handler for Spark

### PR DESCRIPTION
**Pull request by amanraj2520**
### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by amanraj2520** [comment]
@yaooqinn @pan3793

Can you please review this and approve the workflows.

**Comment by zhouyifan279** [comment]
@amanraj2520 Could you please elaborate this PR ? It seems difficult to infer the purpose from the code.

**Comment by yaooqinn** [comment]
Hi @amanraj2520. I'm terribly sorry that I missed this pull request.

Can we make the CI green?

**Comment by yaooqinn** [comment]
Can we tell us the difference between this handler and ranger default ones https://cwiki.apache.org/confluence/display/RANGER/Ranger+Audit+Schema? And How to use this Audit handler?

**Pull request closed without merging**
