### PR TITLE
[DOCS] Fix rst syntax of missing blank line after code-block

### PR DESCRIPTION
**Pull request by pan3793**
# :mag: Description
## Issue References 🔗

This pull request fixes a rst syntax of missing blank line after code-block

## Describe Your Solution 🔧

Add a blank line.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:
image

#### Behavior With This Pull Request :tada:
image

#### Related Unit Tests

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [ ] Pull request title is okay.
- [ ] No license issues.
- [ ] Milestone correctly set?
- [ ] Test coverage is ok
- [ ] Assignees are selected.
- [ ] Minimum number of approvals
- [ ] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by wForget** [comment]
https://github.com/apache/kyuubi/blob/51c3e0372feee5e7dd8983f85076242c4a5fed40/docs/connector/spark/delta_lake_with_azure_blob.rst?plain=1#L173-L174 there is a similar issue

**Review by cxzl25 — APPROVED** [review]

**Comment by pan3793** [comment]
@wForget thanks for checking, I search with keywords `.. code-block::` and fixed all issues i found now.

**Review by wForget — APPROVED** [review]

**Comment by pan3793** [comment]
Merged to master/1.8/1.7

**Comment by yaooqinn** [comment]
> Committer Pre-Merge Checklist 

Consider fulfilling the list next time, guys

**Comment by pan3793** [comment]
> Consider fulfilling the list next time

thanks for reminding.

**Pull request closed without merging**
