### PR TITLE
[KYUUBI #4686] KubernetesApplicationOperation should not support client deploy mode for spark engine

### PR DESCRIPTION
**Pull request by zwangsheng**
### _Why are the changes needed?_

Skip check spark client deploy-mode engine, to avoid APP_NOT_FOUND cause fail.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by zwangsheng** [comment]
cc @pan3793 @wForget @turboFei

**Comment by ulysses-you** [comment]
@zwangsheng the failed test seems related ?

**Comment by zwangsheng** [comment]
> @zwangsheng the failed test seems related ?

Thanks for remind, here add deployMode to `appMgrInfo`.

Since KubernetesApplicationOperator not support client deploy mode, remove related test, which was ignored .

**Comment by zwangsheng** [comment]
As failed unit test not is related, ready to review ping @wForget @turboFei @pan3793 @ulysses-you

**Pull request closed without merging**
