### PR TITLE
Use "(none)" placeholder for default value of un-preset configs on confing doc page

### PR DESCRIPTION
**Pull request by bowenliang123**
# :mag: Description
## Issue References 🔗

As descirbed.

## Describe Your Solution 🔧

- Replace the placeholder for default value of un-preset configs on doc page, changed from `<undefined>` to `(none)`
- The `(none)` placeholder style is also used in the docs of
    - Spark : https://spark.apache.org/docs/latest/configuration.html
    - Flink : https://nightlies.apache.org/flink/flink-docs-master/docs/deployment/config/
    - Trino (as `NONE`): https://trino.io/docs/current/admin/properties.html
- Only affects the config doc page, no functional changes.

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:
No functional changes.

Config doc page:
image

#### Behavior With This Pull Request :tada:
No functional changes.

Config doc page:
image

#### Related Unit Tests

---

# Checklists
## 📝 Author Self Checklist

- [x] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [ ] Pull request title is okay.
- [ ] No license issues.
- [ ] Milestone correctly set?
- [ ] Test coverage is ok
- [ ] Assignees are selected.
- [ ] Minimum number of approvals
- [ ] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by yaooqinn** [comment]
> Only affects the config doc page, no functional changes

Could this be an unnotified breaking change, for example, the return value from retrieving an unset configuration?

BTW, (none) is only manually used on Spark's doc side. For its code side, it uses `<undefined>`

FYI, https://github.com/apache/spark/pull/19974

**Comment by yaooqinn** [comment]
BTW, it seems that `📝 Committer Pre-Merge Checklist` is not welcomed at all.

**Comment by bowenliang123** [comment]
> > Only affects the config doc page, no functional changes
> 
> Could this be an unnotified breaking change, for example, the return value from retrieving an unset configuration?
> 
> BTW, (none) is only manually used on Spark's doc side. For its code side, it uses `<undefined>`
> 
> FYI, [apache/spark#19974](https://github.com/apache/spark/pull/19974)

Let me think again. And if you have worries in this PR, feel free to revert it any time.

**Comment by yaooqinn** [comment]
If it's only related to doc change, I guess we can either optimize the CSS style or map <undefined> to (none) in the test scope for doc generation. Let's revert it first as it might contain unexpected behaviors

**Pull request closed without merging**
