### PR TITLE
[AUTHZ] Check USE permissions for DESCRIBE FUNCTION

### PR DESCRIPTION
**Pull request by Yikf**
### _Why are the changes needed?_

Fix a bug, The `DESCRIBE FUNCTION` syntax should also be checked for USE permissions. However, prior to this PR, the syntax was not checked for any permissions

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

### _Was this patch authored or co-authored using generative AI tooling?_

No

### CODE REVIEW

**Comment by bowenliang123** [comment]
LGTM overall. Is there any positive test case for allowing users to describe functions?

**Comment by bowenliang123** [comment]
also cc @packyan

**Comment by packyan** [comment]
LGTM

**Review by bowenliang123 — APPROVED** [review]

**Comment by bowenliang123** [comment]
Thanks, merged to master.

**Pull request closed without merging**
