### PR TITLE
[Improvement] Introduce code formatting for `*.g4` Antlr4 grammar files

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

- introduce code formatting for Antlr4 files (eg. for KyuubiSql grammar) using `antlr4Formatter` from `spotless-maven-plugin` (doc: https://github.com/diffplug/spotless/tree/main/plugin-maven#antlr4)

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
To be honest, I do not like this new style. Here are my thoughts:
1.  the new style just use more blank line which make it un-readable
2. the end on line `#xxx` is not aligned
3. the current style follows Spark

**Comment by bowenliang123** [comment]
> To be honest, I do not like this new style. Here are my thoughts:
> 
> 1. the new style just use more blank line which make it un-readable
> 2. the end on line `#xxx` is not aligned
> 3. the current style follows Spark

Thanks for reviewing, and I agree with the points you listed.
The rough idea of this PR is to bring auto-formatting to Antlr files, but currently no more options supported to align with the style we expected.

Shall we just close this PR ?

**Comment by ulysses-you** [comment]
yeah, I think so. We can re-open it when we find a better way.

**Comment by bowenliang123** [comment]
OK, closing this PR. Thx.
Btw, we are not expecting a better solution for Antlr styling from the future version of `spotless-maven-plugin`, since from `2.31.0` it requires Java 11+ we are now pinning it to `2.30.0`.

**Pull request closed without merging**
