### PR TITLE
Bump doc build dependencies

### PR DESCRIPTION
**Pull request by bowenliang123**
# :mag: Description
## Issue References 🔗

As descirbed.

## Describe Your Solution 🔧

- Bump pip dependencies' version of doc building tools
    - sphinx 4.5.0 -> 7.2.6
    - sphinx-book-theme 0.3.3-> 1.1.0
    - markdown 3.4.1-> 3.5.1
- Upgraded `sphinx-book-theme` brings 
    - dark mode support (light/dark/system)
    - new search bar style
    - less text hits shown in searched results

## Types of changes :bookmark:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Behavior Without This Pull Request :coffin:
image

image

#### Behavior With This Pull Request :tada:
image

image

image

#### Related Unit Tests

---

# Checklists
## 📝 Author Self Checklist

- [ ] My code follows the [style guidelines](https://kyuubi.readthedocs.io/en/master/contributing/code/style.html) of this project
- [x] I have performed a self-review
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] This patch was not authored or co-authored using [Generative Tooling](https://www.apache.org/legal/generative-tooling.html)

## 📝 Committer Pre-Merge Checklist

- [x] Pull request title is okay.
- [x] No license issues.
- [ ] Milestone correctly set?
- [x] Test coverage is ok
- [ ] Assignees are selected.
- [x] Minimum number of approvals
- [x] No changes are requested

**Be nice. Be informative.**

### CODE REVIEW

**Comment by pan3793** [comment]
I remember the previous try failed https://github.com/apache/kyuubi/pull/4649

**Comment by bowenliang123** [comment]
> I remember the previous try failed #4649

I attached the screenshot of the config page to PR description. Have a check.

**Review by yaooqinn — APPROVED** [review]

**Comment by turboFei** [comment]
thanks, merged to 1.9.0

**Comment by pan3793** [comment]
Cherry-picked to branch-1.8(1.8.2) to recover docs

**Pull request closed without merging**
