### PR TITLE
[KYUUBI #5573] Delete parts of the Kyuubi Web UI that are not useful

### PR DESCRIPTION
**Pull request by zwangsheng**
### _Why are the changes needed?_

As title and make Web UI more clean.

And as Contact Us page and Overview page will do refactor later, so remain these.

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/contributing/code/testing.html#running-tests) locally before make a pull request

截屏2023-10-31 15 30 37

### _Was this patch authored or co-authored using generative AI tooling?_

No

### CODE REVIEW

**Comment by zwangsheng** [comment]
FYI @zhaohehuhu

**Comment by pan3793** [comment]
The overview page is hardcoded now, can we replace it with some meaningful information?

**Comment by pan3793** [comment]
Let's remove the "Contact Us" too

**Comment by yaooqinn** [comment]
image

Not related to this PR, can we change `Apache Kyuubi Dashboard` to the runtime version?

**Comment by zwangsheng** [comment]
> The overview page is hardcoded now, can we replace it with some meaningful information?

@pan3793 , right, I'll be revamping this page in the next few days

> Let's remove the "Contact Us" too

Keep the page in this PR for now, in order to transform it into a footer later.

**Comment by zwangsheng** [comment]
> Not related to this PR, can we change `Apache Kyuubi Dashboard` to the runtime version?

Sure, i'll create an Issue and then change that part later.

**Review by pan3793 — APPROVED** [review]
LGTM, would you please update the screenshot with your latest change?

**Comment by zwangsheng** [comment]
> LGTM, would you please update the screenshot with your latest change?

Sure, updated.

**Pull request closed without merging**
