### PR TITLE
Bump scala-maven-plugin from 4.6.1 to 4.8.0

### PR DESCRIPTION
**Pull request by bowenliang123**
### _Why are the changes needed?_

Bump versions of maven plugins,
- `scala-maven-plugin` from `4.6.1` to `4.8.0` (diff: https://github.com/davidB/scala-maven-plugin/compare/4.6.1...4.8.0)

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.apache.org/docs/latest/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
it's preferred to separate the PR, if we meet bugs in one of them, we can revert independently.

**Comment by bowenliang123** [comment]
> it's preferred to separate the PR, if we meet bugs in one of them, we can revert independently.

Alright,  let me split these changes into 6 small PR.

**Comment by bowenliang123** [comment]
> it's preferred to separate the PR, if we meet bugs in one of them, we can revert independently.

Addressed. Bump a single plugin `scala-maven-plugin` in this PR.

**Comment by Yikf** [comment]
thanks, merged to master

**Pull request closed without merging**
