### PR TITLE
Fix the wrong parsing of jvm parameters in jdbc url.

### PR DESCRIPTION
**Pull request by imperio-wxm**
### _Why are the changes needed?_
The wrong parsing of jvm parameters in jdbc url.

For example:
```shell
jdbc:kyuubi://127.0.0.1:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=kyuubi;user=tom?spark.driver.memory=8G;spark.driver.extraJavaOptions=-Xss256m -XX:+PrintGCDetails -XX:HeapDumpPath=/heap.hprof
```
Now because the regex `([^;]*)=([^;]*);?` only matches `=`, resulting in wrong parsing:
```shell
<spark.driver.memory, 8G>
<spark.driver.extraJavaOptions=-Xss256m -XX:+PrintGCDetails -XX:HeapDumpPath, /heap.hprof>
```

The correct parsing should be:
```shell
<spark.driver.memory, 8G>
<spark.driver.extraJavaOptions, -Xss256m -XX:+PrintGCDetails -XX:HeapDumpPath=/heap.hprof>
```

This PR change `org.apache.kyuubi.jdbc.hive.Utils` and added unit test in `org.apache.kyuubi.jdbc.hive.UtilsTest`.

### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by bowenliang123** [comment]
Good catch.  Do you know how the other projects do the URL parsing ?

And some improvements to do,
1. fix style violations, by running `dev/reformat`
2. use `java.net.URLEncoder` instead of `UrlUtils` from sun's private packages

**Comment by imperio-wxm** [comment]
@bowenliang123  Thanks for your suggestion, I will improve these two parts.

**Comment by pan3793** [comment]
Kindly ping @imperio-wxm, we are during 1.7.0 release cycle, do you have time to address the comments to make this PR get in?

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Thanks, merged to master/1.7/1.6

**Pull request closed without merging**
