### PR TITLE
[KYUUBI #4876] Fix flaky test BackendServiceMetricSuite

### LINKED ISSUE #4876: [TEST] Flaky test BackendServiceMetricSuite
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What kind of test improve?

- [X] Fix flaky tests.
- [ ] Fix bug in tests.
- [ ] Increase test coverage.
- [ ] Other kinds of test improve.

### Describe the issues of the existing tests or improvements for new tests

```
BackendServiceMetricSuite:
- backend service metric test *** FAILED ***
  The code passed to eventually never returned normally. Attempted 70 times over 1.0013718745666667 minutes. Last failure message: 0 was not greater than 0. (BackendServiceMetricSuite.scala:66)
```

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [X] No. I cannot submit a PR at this time.

### PR DESCRIPTION
**Pull request by lightning-L**
### _Why are the changes needed?_

Close #4876

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] [Run test](https://kyuubi.readthedocs.io/en/master/develop_tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by pan3793** [comment]
Thanks for digging and fixing this flaky test. And it's more easily fail on JDK 17, which proves the JDK 17 is faster :)

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
@lightning-L please use script `dev/merge_kyuubi_pr.py` to merge PR, which reserves more information in git commit message, and simplifies the backporting process.

**Comment by pan3793** [comment]
@lightning-L I suppose this PR should be cherry-picked to branch-1.7, and don't forget to update the milestone after PR is merged.

**Comment by lightning-L** [comment]
manually merged to branch-1.7: https://github.com/apache/kyuubi/pull/4926

**Comment by lightning-L** [comment]
sorry, will use the script next time...

**Pull request merged**
